import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { CentralDocumentViewerDialog, type CentralDocumentViewerFile } from './CentralDocumentViewerDialog';
import { apiService } from '@/services/api.service';
import { documentManagementService } from '@/services/document-management.service';
import { savePdfCopy } from '@/lib/save-pdf-copy';

const { exportAnnotationState, exportAnnotatedPdfBlob } = vi.hoisted(() => ({
  exportAnnotationState: vi.fn(), exportAnnotatedPdfBlob: vi.fn(),
}));
vi.mock('next/dynamic', () => ({ default: () => React.forwardRef(function PdfMock(
  props: { fileData?: Uint8Array; fileName?: string }, ref
) {
  React.useImperativeHandle(ref, () => ({ exportAnnotationState, exportAnnotatedPdfBlob }));
  return <div data-testid="pdf-bytes">{props.fileName}:{Array.from(props.fileData || []).join(',')}</div>;
}) }));
vi.mock('@/lib/save-pdf-copy', () => ({ savePdfCopy: vi.fn() }));
vi.mock('@/services/api.service', () => ({ apiService: { downloadBlob: vi.fn() } }));
vi.mock('@/services/document-management.service', () => ({ documentManagementService: { downloadVersionFile: vi.fn(), downloadRecordContent: vi.fn() } }));
const bytes = new Uint8Array([37, 80, 68, 70]);
const generated: CentralDocumentViewerFile = { title: 'PO-1', fileName: 'PO-1.pdf', pdfData: bytes, contentType: 'application/pdf' };

beforeEach(() => vi.clearAllMocks());
describe('central PDF preview byte source', () => {
  it('renders an already-generated PDF without a URL, download, popup or refetch', async () => {
    const popup = vi.spyOn(window, 'open').mockReturnValue(null);
    render(<CentralDocumentViewerDialog open file={generated} onOpenChange={vi.fn()} enableAnnotations={false} />);
    expect(await screen.findByTestId('pdf-bytes')).toHaveTextContent('PO-1.pdf:37,80,68,70');
    expect(apiService.downloadBlob).not.toHaveBeenCalled();
    expect(popup).not.toHaveBeenCalled();
    expect(screen.getByText('Read only')).toBeInTheDocument();
    popup.mockRestore();
  });
  it('never lets supplied bytes bypass a protected route', async () => {
    vi.mocked(apiService.downloadBlob).mockRejectedValue(new Error('Access denied for this voucher.'));
    render(<CentralDocumentViewerDialog open file={{ ...generated, repositoryPath: '/api/inventory/requisitions/issue-vouchers/v1/download' }} onOpenChange={vi.fn()} />);
    expect(await screen.findByText('Access denied for this voucher.')).toBeInTheDocument();
    expect(apiService.downloadBlob).toHaveBeenCalledWith('/inventory/requisitions/issue-vouchers/v1/download');
    expect(screen.queryByTestId('pdf-bytes')).not.toBeInTheDocument();
  });
  it('replaces generated bytes on a different file and clears them when closed', async () => {
    const props = { onOpenChange: vi.fn(), enableAnnotations: false };
    const { rerender } = render(<CentralDocumentViewerDialog open file={generated} {...props} />);
    await screen.findByTestId('pdf-bytes');
    rerender(<CentralDocumentViewerDialog open file={{ title: 'PO-2', fileName: 'PO-2.pdf', pdfData: new Uint8Array([2]) }} {...props} />);
    await waitFor(() => expect(screen.getByTestId('pdf-bytes')).toHaveTextContent('PO-2.pdf:2'));
    rerender(<CentralDocumentViewerDialog open={false} file={null} {...props} />);
    await waitFor(() => expect(screen.queryByTestId('pdf-bytes')).not.toBeInTheDocument());
  });
  it('does not render an empty generated PDF as a successful preview', () => {
    render(<CentralDocumentViewerDialog open file={{ ...generated, pdfData: new Uint8Array() }} onOpenChange={vi.fn()} />);
    expect(screen.getByText('No viewable file linked')).toBeInTheDocument();
    expect(screen.queryByTestId('pdf-bytes')).not.toBeInTheDocument();
  });
  it('saves annotations through DMS while keeping local save-copy unavailable in edit mode', async () => {
    const secured = { ...generated, documentRecordId: 'record-1', versionId: 'version-1' };
    const annotatedPdf = new Blob(['annotated'], { type: 'application/pdf' });
    vi.mocked(documentManagementService.downloadVersionFile).mockResolvedValue({ arrayBuffer: async () => bytes.buffer } as Blob);
    exportAnnotationState.mockResolvedValue('{"annotations":[]}');
    exportAnnotatedPdfBlob.mockResolvedValue(annotatedPdf);
    const onSaveAnnotations = vi.fn().mockResolvedValue(undefined);
    render(<CentralDocumentViewerDialog open file={secured} onOpenChange={vi.fn()} enableSaveCopy onSaveAnnotations={onSaveAnnotations} />);
    await screen.findByTestId('pdf-bytes');
    fireEvent.click(screen.getByRole('button', { name: 'Save annotations' }));
    await waitFor(() => expect(onSaveAnnotations).toHaveBeenCalledWith(secured, '{"annotations":[]}', annotatedPdf));
    expect(screen.queryByRole('button', { name: 'Save PDF as...' })).not.toBeInTheDocument();
    expect(savePdfCopy).not.toHaveBeenCalled();
  });
  it('saves a read-only QS copy without invoking annotation persistence', async () => {
    vi.mocked(savePdfCopy).mockResolvedValue('saved');
    const onSaveAnnotations = vi.fn();
    render(<CentralDocumentViewerDialog open file={generated} onOpenChange={vi.fn()} enableSaveCopy enableAnnotations={false} onSaveAnnotations={onSaveAnnotations} />);
    fireEvent.click(await screen.findByRole('button', { name: 'Save PDF as...' }));
    expect(await screen.findByRole('status')).toHaveTextContent('PDF saved successfully.');
    expect(savePdfCopy).toHaveBeenCalledWith(bytes, 'PO-1.pdf');
    expect(onSaveAnnotations).not.toHaveBeenCalled();
    expect(screen.queryByRole('button', { name: 'Save annotations' })).not.toBeInTheDocument();
  });
});
