import React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { CentralDocumentViewerDialog, type CentralDocumentViewerFile } from './CentralDocumentViewerDialog';
import { apiService } from '@/services/api.service';

vi.mock('next/dynamic', () => ({ default: () => (props: { fileData?: Uint8Array; fileName?: string }) =>
  <div data-testid="pdf-bytes">{props.fileName}:{Array.from(props.fileData || []).join(',')}</div> }));
vi.mock('@/services/api.service', () => ({ apiService: { downloadBlob: vi.fn() } }));
vi.mock('@/services/document-management.service', () => ({ documentManagementService: { downloadVersionFile: vi.fn(), downloadRecordContent: vi.fn() } }));
const bytes = new Uint8Array([37, 80, 68, 70]);
const generated: CentralDocumentViewerFile = { title: 'PO-1', fileName: 'PO-1.pdf', pdfData: bytes, contentType: 'application/pdf' };

beforeEach(() => vi.clearAllMocks());
describe('central PDF preview byte source', () => {
  it('renders an already-generated PDF without a URL, download, popup or refetch', async () => {
    const popup = vi.spyOn(window, 'open').mockReturnValue(null);
    render(<CentralDocumentViewerDialog open file={generated} onOpenChange={vi.fn()} enableAnnotations={false} />);
    expect(await screen.findByTestId('pdf-bytes')).toHaveTextContent('PO-1.pdf:37,80,68,70');
    expect(apiService.downloadBlob).not.toHaveBeenCalled();
    expect(popup).not.toHaveBeenCalled();
    expect(screen.getByText('Read only')).toBeInTheDocument();
    popup.mockRestore();
  });
  it('never lets supplied bytes bypass a protected route', async () => {
    vi.mocked(apiService.downloadBlob).mockRejectedValue(new Error('Access denied for this voucher.'));
    render(<CentralDocumentViewerDialog open file={{ ...generated, repositoryPath: '/api/inventory/requisitions/issue-vouchers/v1/download' }} onOpenChange={vi.fn()} />);
    expect(await screen.findByText('Access denied for this voucher.')).toBeInTheDocument();
    expect(apiService.downloadBlob).toHaveBeenCalledWith('/inventory/requisitions/issue-vouchers/v1/download');
    expect(screen.queryByTestId('pdf-bytes')).not.toBeInTheDocument();
  });
  it('replaces generated bytes on a different file and clears them when closed', async () => {
    const props = { onOpenChange: vi.fn(), enableAnnotations: false };
    const { rerender } = render(<CentralDocumentViewerDialog open file={generated} {...props} />);
    await screen.findByTestId('pdf-bytes');
    rerender(<CentralDocumentViewerDialog open file={{ title: 'PO-2', fileName: 'PO-2.pdf', pdfData: new Uint8Array([2]) }} {...props} />);
    await waitFor(() => expect(screen.getByTestId('pdf-bytes')).toHaveTextContent('PO-2.pdf:2'));
    rerender(<CentralDocumentViewerDialog open={false} file={null} {...props} />);
    await waitFor(() => expect(screen.queryByTestId('pdf-bytes')).not.toBeInTheDocument());
  });
  it('does not render an empty generated PDF as a successful preview', () => {
    render(<CentralDocumentViewerDialog open file={{ ...generated, pdfData: new Uint8Array() }} onOpenChange={vi.fn()} />);
    expect(screen.getByText('No viewable file linked')).toBeInTheDocument();
    expect(screen.queryByTestId('pdf-bytes')).not.toBeInTheDocument();
  });
});
