using System;
using System.ComponentModel.DataAnnotations;

namespace ErpSystem.Core.DTOs.Finance
{
    /// <summary>
    /// READ DTO: Represents a segment lookup value as returned by the API.
    /// 
    /// This is what the frontend will typically consume when:
    /// - Building dropdown lists for segment values (e.g. Departments, Cost Centers)
    /// - Displaying existing configuration in admin/configuration screens
    /// - Validating that an account's segment value is still valid/active
    /// 
    /// SOURCE: <see cref="ErpSystem.Core.Entities.Finance.SegmentLookupValue"/>
    /// PATTERN:
    /// - Includes Id, TenantId and all main domain properties
    /// - Includes audit fields from BaseEntity for troubleshooting and history
    /// - Designed to be stable for other modules that depend on Finance
    /// </summary>
    public class SegmentLookupValueDto
    {
        /// <summary>
        /// Unique identifier of this lookup value (GUID).
        /// 
        /// - Generated by the system when the record is created.
        /// - Used by the frontend as the primary key (e.g. in dropdown values).
        /// - Passed back to the API when updating or deleting this record.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Tenant identifier (multi-tenancy support).
        /// 
        /// IMPORTANT:
        /// - System uses this to enforce tenant isolation.
        /// - Not supplied by clients on create/update – it is derived from the
        ///   authenticated user context (<c>_currentUserService.TenantId</c>).
        /// - Exposed here only for read scenarios, logging, and admin tooling.
        /// </summary>
        public Guid TenantId { get; set; }

        /// <summary>
        /// Reference to the segment structure (definition) this value belongs to.
        /// 
        /// Example:
        /// - SegmentStructure: "Department" (Position 2, Length 3)
        /// - SegmentLookupValue: "FIN" / "HR" / "IT" etc.
        /// 
        /// Frontend usage:
        /// - Used when filtering values by segment (e.g. load all values for Department).
        /// - Typically bound to a hidden field when editing a lookup value.
        /// </summary>
        public Guid SegmentStructureId { get; set; }

        /// <summary>
        /// The actual code/value that will appear in account numbers.
        /// 
        /// Examples:
        /// - "HR", "IT", "FIN", "SALES"
        /// - Must respect <c>SegmentLength</c> from <c>AccountSegmentStructure</c>.
        /// 
        /// Frontend usage:
        /// - This is the code the user selects when defining or editing a GL Account.
        /// - Displayed in dropdowns and type-ahead fields.
        /// </summary>
        public string SegmentValue { get; set; } = string.Empty;

        /// <summary>
        /// Full descriptive name for the value.
        /// 
        /// Examples:
        /// - "Human Resources Department"
        /// - "Information Technology"
        /// - "Sales – North Region"
        /// 
        /// Frontend usage:
        /// - Displayed next to <see cref="SegmentValue"/> in dropdowns and grids
        ///   (e.g. "FIN – Finance Department").
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Optional parent value, used to model hierarchical structures.
        /// 
        /// Examples:
        /// - "IT" as parent of "IT-SUPPORT" and "IT-DEV"
        /// - "SALES" as parent of "SALES-NORTH" and "SALES-SOUTH"
        /// 
        /// Frontend usage:
        /// - Used when building cascaded dropdowns or tree views.
        /// - NULL when this value is a top-level node.
        /// </summary>
        public Guid? ParentValueId { get; set; }

        /// <summary>
        /// Date from which this value becomes valid/available for use.
        /// 
        /// Typical workflow:
        /// - Can be set to a future date when a new department will start operating.
        /// - System/UI should prevent usage in accounts or transactions before this date.
        /// </summary>
        public DateTime EffectiveDate { get; set; }

        /// <summary>
        /// Optional date after which this value can no longer be used for new accounts.
        /// 
        /// Notes:
        /// - Existing accounts and historical transactions remain valid.
        /// - Frontend may choose to hide/disable values that are expired.
        /// </summary>
        public DateTime? ExpiryDate { get; set; }

        /// <summary>
        /// Active status flag.
        /// 
        /// - True  = value is available for new accounts (subject to Effective/Expiry dates).
        /// - False = value is "retired" and cannot be used for new accounts.
        /// 
        /// UI Guidance:
        /// - Common pattern: show only active values in standard dropdowns.
        /// - Provide an "Include inactive" toggle for admin/config screens.
        /// </summary>
        public bool IsActive { get; set; }

        /// <summary>
        /// Display order used to control the sort sequence in dropdowns and reports.
        /// 
        /// - Lower numbers appear first.
        /// - Values with the same DisplayOrder can then be sorted by SegmentValue.
        /// </summary>
        public int DisplayOrder { get; set; }

        /// <summary>
        /// Optional notes or instructions for this segment value.
        /// 
        /// Examples:
        /// - "Department is being phased out this year."
        /// - "Use only for legacy projects."
        /// </summary>
        public string? Notes { get; set; }

        // ---------------------------------------------------------------------
        // AUDIT FIELDS (from BaseEntity)
        // ---------------------------------------------------------------------

        /// <summary>
        /// Timestamp when this lookup value was created (UTC).
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Timestamp when this lookup value was last updated (UTC).
        /// NULL if never updated after creation.
        /// </summary>
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// Username/identifier of the user who created this record.
        /// </summary>
        public string? CreatedBy { get; set; }

        /// <summary>
        /// Username/identifier of the user who last updated this record.
        /// </summary>
        public string? UpdatedBy { get; set; }
    }

    /// <summary>
    /// CREATE DTO: Represents payload required to create a new segment lookup value.
    /// 
    /// Usage:
    /// - POST /api/finance/segment-lookup-values
    /// - Used by configuration UIs when adding new departments, cost centers, etc.
    /// 
    /// DESIGN:
    /// - No Id or audit fields (system-generated).
    /// - TenantId derived from current user; not supplied by clients.
    /// - Validation rules ([Required], [MaxLength]) mirror entity constraints.
    /// </summary>
    public class SegmentLookupValueCreateDto
    {
        /// <summary>
        /// Segment structure this lookup value belongs to.
        /// 
        /// Example:
        /// - The GUID of the "Department" segment definition.
        /// 
        /// Validation:
        /// - Required – backend will validate that the referenced segment exists
        ///   and that it is configured to use a lookup table.
        /// </summary>
        [Required]
        public Guid SegmentStructureId { get; set; }

        /// <summary>
        /// The actual code/value that will appear in the account number.
        /// 
        /// Examples:
        /// - "FIN", "HR", "IT"
        /// 
        /// Validation:
        /// - Required
        /// - Max length 10 characters (must also respect SegmentLength of the segment).
        /// - Additional cross-field validation (length match) will be performed
        ///   in the service layer.
        /// </summary>
        [Required]
        [MaxLength(10)]
        public string SegmentValue { get; set; } = string.Empty;

        /// <summary>
        /// Descriptive name to display alongside the code.
        /// 
        /// Examples:
        /// - "Finance Department"
        /// - "Human Resources"
        /// 
        /// Validation:
        /// - Required
        /// - Max length 200 characters.
        /// </summary>
        [Required]
        [MaxLength(200)]
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Optional parent lookup value to build a hierarchy.
        /// 
        /// - NULL for top-level values.
        /// - If supplied, backend will validate that the parent belongs to the
        ///   same segment structure (to avoid cross-segment hierarchies).
        /// </summary>
        public Guid? ParentValueId { get; set; }

        /// <summary>
        /// Date from which this value becomes valid.
        /// 
        /// Defaults:
        /// - If not supplied, backend may default to today's UTC date.
        /// 
        /// Frontend:
        /// - Use a date picker.
        /// - For "immediately valid" values, you can omit or set to today's date.
        /// </summary>
        public DateTime? EffectiveDate { get; set; }

        /// <summary>
        /// Optional expiry date, after which the value cannot be used for new accounts.
        /// 
        /// Validation:
        /// - If supplied, must be greater than or equal to <see cref="EffectiveDate"/>.
        ///   (This is enforced in the service layer.)
        /// </summary>
        public DateTime? ExpiryDate { get; set; }

        /// <summary>
        /// Initial active status.
        /// 
        /// Typical scenarios:
        /// - Create as active (default) for immediate use.
        /// - Create as inactive if you are setting up future values or templates.
        /// </summary>
        public bool IsActive { get; set; } = true;

        /// <summary>
        /// Initial display order for this value in dropdowns and lists.
        /// 
        /// Recommendations:
        /// - Frontend may start from 10, 20, 30... to allow easy insertion between.
        /// - 0 is allowed and simply indicates "no specific ordering".
        /// </summary>
        public int DisplayOrder { get; set; } = 0;

        /// <summary>
        /// Optional notes or remarks about this value.
        /// 
        /// Examples:
        /// - "Use for legacy projects only."
        /// - "Created for FY2025 restructuring."
        /// </summary>
        [MaxLength(1000)]
        public string? Notes { get; set; }
    }

    /// <summary>
    /// UPDATE DTO: Represents payload required to update an existing segment lookup value.
    /// 
    /// Usage:
    /// - PUT /api/finance/segment-lookup-values/{id}
    /// - Used by configuration UIs when editing departments, cost centers, etc.
    /// 
    /// DESIGN:
    /// - Includes Id so the service can identify which record to update.
    /// - Other fields mirror <see cref="SegmentLookupValueCreateDto"/> and
    ///   follow the same validation rules.
    /// </summary>
    public class SegmentLookupValueUpdateDto
    {
        /// <summary>
        /// Unique identifier of the lookup value being updated.
        /// 
        /// - Must match the route parameter in the API (for consistency).
        /// - Backend will typically validate that the route Id = body Id.
        /// </summary>
        [Required]
        public Guid Id { get; set; }

        /// <summary>
        /// Segment structure this lookup value belongs to.
        /// 
        /// It is common to keep this fixed, but the API allows changing it if
        /// business rules permit (service layer will enforce constraints).
        /// </summary>
        [Required]
        public Guid SegmentStructureId { get; set; }

        /// <summary>
        /// Updated code/value used in account numbers.
        /// 
        /// WARNING:
        /// - Changing codes for values already in use may have reporting/audit impact.
        /// - Service layer may disallow changes if the value is already used in accounts.
        /// </summary>
        [Required]
        [MaxLength(10)]
        public string SegmentValue { get; set; } = string.Empty;

        /// <summary>
        /// Updated descriptive name.
        /// 
        /// - Safe to change even when value is already used.
        /// - Common scenario: rename "Finance" to "Finance & Strategy".
        /// </summary>
        [Required]
        [MaxLength(200)]
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Updated parent lookup value for hierarchy.
        /// 
        /// - Can be changed to re-parent nodes in the hierarchy.
        /// - NULL to promote a value to top-level.
        /// </summary>
        public Guid? ParentValueId { get; set; }

        /// <summary>
        /// Updated effective date.
        /// 
        /// - Service layer will validate date consistency with historical usage.
        /// - May be used in future enhancements for effective dating logic.
        /// </summary>
        public DateTime? EffectiveDate { get; set; }

        /// <summary>
        /// Updated expiry date.
        /// 
        /// - Common scenario: set an expiry date when phasing out a department.
        /// - Must be greater than or equal to <see cref="EffectiveDate"/> (enforced in service).
        /// </summary>
        public DateTime? ExpiryDate { get; set; }

        /// <summary>
        /// Updated active status.
        /// 
        /// - Set to false to retire this value for new accounts.
        /// - Typically combined with an ExpiryDate for reporting clarity.
        /// </summary>
        public bool IsActive { get; set; } = true;

        /// <summary>
        /// Updated display order.
        /// 
        /// - Use to re-order values in UI without needing to change codes.
        /// </summary>
        public int DisplayOrder { get; set; } = 0;

        /// <summary>
        /// Updated notes or remarks.
        /// </summary>
        [MaxLength(1000)]
        public string? Notes { get; set; }
    }
}
