// <auto-generated />
using System;
using ErpSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpSystem.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpSystem.Core.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3808),
                            IsSystemRole = true,
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3846),
                            IsSystemRole = true,
                            Name = "TenantAdmin",
                            NormalizedName = "TENANTADMIN"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3857),
                            IsSystemRole = true,
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3859),
                            IsSystemRole = true,
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AuthenticationProvider")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LdapDn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_ApplicationUser_Email_Unique")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_ApplicationUser_UserName_Unique")
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Resource");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.EmailSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseTLS")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.PasswordPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MinLength")
                        .HasColumnType("int");

                    b.Property<int?>("PreventReuse")
                        .HasColumnType("int");

                    b.Property<bool>("RequireDigits")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireLowercase")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireSpecialChars")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireUppercase")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("PasswordPolicies");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemPermission")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Category = "User Management",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4071),
                            Description = "View user accounts and details",
                            DisplayName = "View Users",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "users.read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Category = "User Management",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4080),
                            Description = "Create new user accounts",
                            DisplayName = "Create Users",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "users.create"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Category = "User Management",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4085),
                            Description = "Edit existing user accounts",
                            DisplayName = "Update Users",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "users.update"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Category = "User Management",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4089),
                            Description = "Delete user accounts",
                            DisplayName = "Delete Users",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "users.delete"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Category = "Role Management",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4101),
                            Description = "View role definitions",
                            DisplayName = "View Roles",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "roles.read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Category = "Role Management",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4107),
                            Description = "Create new roles",
                            DisplayName = "Create Roles",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "roles.create"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Category = "Role Management",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4112),
                            Description = "Edit existing roles",
                            DisplayName = "Update Roles",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "roles.update"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Category = "Role Management",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4116),
                            Description = "Delete roles",
                            DisplayName = "Delete Roles",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "roles.delete"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Category = "Dashboard & Reports",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4124),
                            Description = "Access main dashboard",
                            DisplayName = "View Dashboard",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "dashboard.read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Category = "Dashboard & Reports",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4132),
                            Description = "Access reporting features",
                            DisplayName = "View Reports",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "reports.read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Category = "Dashboard & Reports",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4142),
                            Description = "Generate custom reports",
                            DisplayName = "Create Reports",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "reports.create"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Category = "Dashboard & Reports",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4146),
                            Description = "Access analytics data",
                            DisplayName = "View Analytics",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "analytics.read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Category = "System Administration",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4156),
                            Description = "Access admin interface",
                            DisplayName = "View Admin",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "admin.read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Category = "System Administration",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4161),
                            Description = "View system settings",
                            DisplayName = "View Settings",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "settings.read"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Category = "System Administration",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4165),
                            Description = "Modify system settings",
                            DisplayName = "Update Settings",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "settings.update"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Category = "System Administration",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4168),
                            Description = "Access audit trail",
                            DisplayName = "View Audit Logs",
                            IsDeleted = false,
                            IsSystemPermission = true,
                            Name = "audit.read"
                        });
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrantedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4209),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4211),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4212),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4213),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000005"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4214),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000006"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4216),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000007"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4217),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000008"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4218),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000009"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4219),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000010"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4221),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000011"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4222),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000012"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4222),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000013"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4223),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000014"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4224),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000015"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4225),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000016"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4225),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4256),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000002"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4259),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4260),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000004"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4261),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000005"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4262),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000006"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4263),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000007"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4263),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000008"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4264),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000009"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4265),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000010"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4266),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000011"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4266),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000012"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4267),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000014"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4268),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000015"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4269),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000016"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4269),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4304),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000003"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4305),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000005"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4307),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000009"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4308),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000010"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4309),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000011"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4310),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000012"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4310),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000013"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4311),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000014"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4312),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000016"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4313),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000001"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4327),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000009"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4328),
                            GrantedBy = "System"
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0000-000000000010"),
                            GrantedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4329),
                            GrantedBy = "System"
                        });
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.Security", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountLockoutMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("CaptchaEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("CaptchaProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HCaptchaSecretKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HCaptchaSiteKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JwtTokenLifetimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaxFailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<int?>("PasswordMaxAge")
                        .HasColumnType("int");

                    b.Property<int>("PasswordMinLength")
                        .HasColumnType("int");

                    b.Property<int?>("PasswordPreventReuse")
                        .HasColumnType("int");

                    b.Property<bool>("PasswordRequireDigits")
                        .HasColumnType("bit");

                    b.Property<bool>("PasswordRequireLowercase")
                        .HasColumnType("bit");

                    b.Property<bool>("PasswordRequireSpecialChars")
                        .HasColumnType("bit");

                    b.Property<bool>("PasswordRequireUppercase")
                        .HasColumnType("bit");

                    b.Property<int>("PreventConcurrentLogin")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitForgotPasswordBlockDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitForgotPasswordMaxAttempts")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitForgotPasswordWindowMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitLoginBlockDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitLoginMaxAttempts")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitLoginWindowMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitRegisterBlockDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitRegisterMaxAttempts")
                        .HasColumnType("int");

                    b.Property<int>("RateLimitRegisterWindowMinutes")
                        .HasColumnType("int");

                    b.Property<string>("RecaptchaSecretKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RecaptchaSiteKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.SecurityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("IpAddress");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("SecurityLogs");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AllowSelfRegistration")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultPriority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Domain")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EnableAutoSelection")
                        .HasColumnType("bit");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDefaultForInternalUsers")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefaultForPublicUsers")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LdapBaseDn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdapBindDn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LdapBindPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LdapEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("LdapPort")
                        .HasColumnType("int");

                    b.Property<string>("LdapServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("PublicRegistrationDomains")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequireEmailVerification")
                        .HasColumnType("bit");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubscriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAudience")
                        .HasColumnType("int");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasFilter("[Domain] IS NOT NULL");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AllowSelfRegistration = false,
                            Code = "DEFAULT",
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3629),
                            DefaultPriority = 10,
                            Description = "Default system tenant",
                            EnableAutoSelection = false,
                            IsDefaultForInternalUsers = false,
                            IsDefaultForPublicUsers = false,
                            IsDeleted = false,
                            LdapEnabled = false,
                            Name = "Default Tenant",
                            RequireEmailVerification = false,
                            Status = 1,
                            UserAudience = 2
                        });
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.TenantModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Configuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DisabledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EnabledDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ModuleName")
                        .IsUnique();

                    b.ToTable("TenantModules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cf13e57-43f3-4237-8ed9-363d038b8c72"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3919),
                            EnabledDate = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3916),
                            IsDeleted = false,
                            ModuleName = "Finance",
                            Status = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("3dd19062-607f-4cbf-84e8-f1e75968b9fd"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3935),
                            EnabledDate = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3935),
                            IsDeleted = false,
                            ModuleName = "HR",
                            Status = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("4b811d7a-9e07-4e5e-b3f3-e753b2abd20d"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3950),
                            EnabledDate = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3949),
                            IsDeleted = false,
                            ModuleName = "Sales",
                            Status = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("13a31a76-13db-4f5b-98aa-97d166bc44c6"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3964),
                            EnabledDate = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3964),
                            IsDeleted = false,
                            ModuleName = "Procurement",
                            Status = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("34707133-62c2-4b25-b604-686f6b767234"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3978),
                            EnabledDate = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3977),
                            IsDeleted = false,
                            ModuleName = "Inventory",
                            Status = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("fbee9da2-a19a-4f08-a03d-9dd29a5471bf"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3990),
                            EnabledDate = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(3990),
                            IsDeleted = false,
                            ModuleName = "Marketing",
                            Status = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("ee1b4fe4-3fdf-4ea2-a4f8-85ab31bd9ed8"),
                            CreatedAt = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4002),
                            EnabledDate = new DateTime(2025, 9, 27, 11, 44, 42, 501, DateTimeKind.Utc).AddTicks(4002),
                            IsDeleted = false,
                            ModuleName = "WorkflowEngine",
                            Status = 1,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.UserTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SuspendedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique();

                    b.ToTable("UserTenants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.ApplicationUser", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.ApplicationUserRole", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpSystem.Core.Entities.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpSystem.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.EmailSettings", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.PasswordPolicy", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpSystem.Core.Entities.ApplicationRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.Security", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.SecurityLog", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpSystem.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.SystemSettings", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.TenantModule", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("TenantModules")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.UserTenant", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.Tenant", "Tenant")
                        .WithMany("UserTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ErpSystem.Core.Entities.ApplicationUser", "User")
                        .WithMany("UserTenants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ErpSystem.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.ApplicationRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");

                    b.Navigation("UserTenants");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ErpSystem.Core.Entities.Tenant", b =>
                {
                    b.Navigation("TenantModules");

                    b.Navigation("UserTenants");
                });
#pragma warning restore 612, 618
        }
    }
}
