using ErpSystem.Core.DTOs.HR.Payroll;
using ErpSystem.Core.Entities.HR.Payroll;

namespace ErpSystem.Core.Interfaces.HR.Services;

public interface IPayrollService
{
    Task<IReadOnlyList<PayrollLegacyMenuItemDto>> GetLegacyMenuAsync(CancellationToken cancellationToken = default);
    Task<PayrollSetupSummaryDto> GetSetupSummaryAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollCodeSetupDto> GetCodeSetupAsync(Guid tenantId, string? codeType = null, CancellationToken cancellationToken = default);
    Task<PayrollCodeTypeDto> UpsertCodeTypeAsync(Guid tenantId, UpsertPayrollCodeTypeDto dto, CancellationToken cancellationToken = default);
    Task<PayrollCodeValueDto> UpsertCodeValueAsync(Guid tenantId, UpsertPayrollCodeValueDto dto, CancellationToken cancellationToken = default);
    Task<PayrollHolidaySetupDto> GetHolidaySetupAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollHolidayDto> UpsertHolidayAsync(Guid tenantId, UpsertPayrollHolidayDto dto, CancellationToken cancellationToken = default);
    Task<PayrollNonWorkingDayDto> UpsertNonWorkingDayAsync(Guid tenantId, UpsertPayrollNonWorkingDayDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollExchangeRateDto>> GetExchangeRatesAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollExchangeRateDto> UpsertExchangeRateAsync(Guid tenantId, UpsertPayrollExchangeRateDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollBankBranchDto>> GetBankBranchesAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollBankBranchDto> UpsertBankBranchAsync(Guid tenantId, UpsertPayrollBankBranchDto dto, CancellationToken cancellationToken = default);
    Task<PayrollLeaveSetupCollectionDto> GetLeaveSetupAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollLeaveSetupDto> UpsertLeaveSetupAsync(Guid tenantId, UpsertPayrollLeaveSetupDto dto, CancellationToken cancellationToken = default);
    Task<PayrollLeaveSetupDetailDto> UpsertLeaveSetupDetailAsync(Guid tenantId, UpsertPayrollLeaveSetupDetailDto dto, CancellationToken cancellationToken = default);
    Task<PayrollOvertimeSetupDto> GetOvertimeSetupAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollOvertimeRangeDto> UpsertOvertimeRangeAsync(Guid tenantId, UpsertPayrollOvertimeRangeDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollLegacyMenuUserDto>> GetLegacyMenuUsersAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollLegacyMenuUserDto> UpsertLegacyMenuUserAsync(Guid tenantId, UpsertPayrollLegacyMenuUserDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollLegacyMenuSecurityDto>> GetMenuSecurityAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollLegacyMenuSecurityDto> UpsertMenuSecurityAsync(Guid tenantId, UpsertPayrollLegacyMenuSecurityDto dto, CancellationToken cancellationToken = default);
    Task<PayrollLegacyMenuUserDto> ChangeLegacyMenuUserPasswordAsync(Guid tenantId, PayrollLegacyPasswordChangeDto dto, CancellationToken cancellationToken = default);
    Task<PayrollCompanySetupDto> GetCompanySetupAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollCompanyProfileDto> UpsertCompanyProfileAsync(Guid tenantId, UpsertPayrollCompanyProfileDto dto, CancellationToken cancellationToken = default);
    Task<PayrollBusinessUnitDto> UpsertBusinessUnitAsync(Guid tenantId, UpsertPayrollBusinessUnitDto dto, CancellationToken cancellationToken = default);
    Task<PayrollCompanyBankerDto> UpsertCompanyBankerAsync(Guid tenantId, UpsertPayrollCompanyBankerDto dto, CancellationToken cancellationToken = default);
    Task<PayrollGradeSetupDto> GetGradeSetupAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollGradeDto> UpsertGradeAsync(Guid tenantId, UpsertPayrollGradeDto dto, CancellationToken cancellationToken = default);
    Task<PayrollGradeNotchDto> UpsertGradeNotchAsync(Guid tenantId, UpsertPayrollGradeNotchDto dto, CancellationToken cancellationToken = default);
    Task<PayrollTaxTableDto> GetTaxTableAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollParameterSetDto> UpsertParameterSetAsync(Guid tenantId, UpsertPayrollParameterSetDto dto, CancellationToken cancellationToken = default);
    Task<PayrollComponentDto> UpsertComponentAsync(Guid tenantId, UpsertPayrollComponentDto dto, CancellationToken cancellationToken = default);
    Task<PayrollComponentRuleDto> UpsertComponentRuleAsync(Guid tenantId, UpsertPayrollComponentRuleDto dto, CancellationToken cancellationToken = default);
    Task<PayrollTaxBandDto> UpsertTaxBandAsync(Guid tenantId, UpsertPayrollTaxBandDto dto, CancellationToken cancellationToken = default);
    Task<PayrollTaxReliefDto> UpsertTaxReliefAsync(Guid tenantId, UpsertPayrollTaxReliefDto dto, CancellationToken cancellationToken = default);
    Task<PayrollPensionSchemeDto> UpsertPensionSchemeAsync(Guid tenantId, UpsertPayrollPensionSchemeDto dto, CancellationToken cancellationToken = default);
    Task<PayrollOvertimePolicyDto> UpsertOvertimePolicyAsync(Guid tenantId, UpsertPayrollOvertimePolicyDto dto, CancellationToken cancellationToken = default);
    Task<PayrollLoanPolicyDto> UpsertLoanPolicyAsync(Guid tenantId, UpsertPayrollLoanPolicyDto dto, CancellationToken cancellationToken = default);
    Task<PayrollBonusPolicyDto> UpsertBonusPolicyAsync(Guid tenantId, UpsertPayrollBonusPolicyDto dto, CancellationToken cancellationToken = default);
    Task<PayrollBonusRuleDto> UpsertBonusRuleAsync(Guid tenantId, UpsertPayrollBonusRuleDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollBonusExceptionDto>> GetBonusExceptionsAsync(Guid tenantId, string? bonusCode = null, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollBonusExceptionDto>> SaveBonusExceptionsAsync(Guid tenantId, PayrollBonusExceptionBulkSaveDto dto, CancellationToken cancellationToken = default);
    Task<PayrollBackpayPolicyDto> UpsertBackpayPolicyAsync(Guid tenantId, UpsertPayrollBackpayPolicyDto dto, CancellationToken cancellationToken = default);
    Task<PayrollBackpayRuleDto> UpsertBackpayRuleAsync(Guid tenantId, UpsertPayrollBackpayRuleDto dto, CancellationToken cancellationToken = default);
    Task<PayrollBackpayExceptionDto> UpsertBackpayExceptionAsync(Guid tenantId, UpsertPayrollBackpayExceptionDto dto, CancellationToken cancellationToken = default);
    Task<PayrollJournalMappingDto> UpsertJournalMappingAsync(Guid tenantId, UpsertPayrollJournalMappingDto dto, CancellationToken cancellationToken = default);

    Task<IReadOnlyList<PayrollEmployeeProfileDto>> GetEmployeeProfilesAsync(Guid tenantId, string? searchTerm = null, CancellationToken cancellationToken = default);
    Task<PayrollEmployeeProfileDto> UpsertEmployeeProfileAsync(Guid tenantId, UpsertPayrollEmployeeProfileDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollLoanDto>> GetLoansAsync(Guid tenantId, string? employeeNumber = null, bool includeInactive = false, CancellationToken cancellationToken = default);
    Task<PayrollLoanDto> UpsertLoanAsync(Guid tenantId, UpsertPayrollLoanDto dto, CancellationToken cancellationToken = default);
    Task<PayrollLoanRepaymentDto> PostLoanRepaymentAsync(Guid tenantId, PayrollLoanRepaymentRequestDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollSalaryAdvanceDto>> GetSalaryAdvancesAsync(Guid tenantId, DateTime? fromDate = null, DateTime? toDate = null, string? employeeNumber = null, CancellationToken cancellationToken = default);
    Task<PayrollSalaryAdvanceDto> UpsertSalaryAdvanceAsync(Guid tenantId, UpsertPayrollSalaryAdvanceDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollEmployeeTaxReliefDto>> GetEmployeeTaxReliefsAsync(Guid tenantId, string? reliefCode = null, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollEmployeeTaxReliefDto>> SaveEmployeeTaxReliefsAsync(Guid tenantId, PayrollEmployeeTaxReliefBulkSaveDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollEmployeeComponentExceptionDto>> GetEmployeeComponentExceptionsAsync(Guid tenantId, Guid? payrollComponentId = null, string? componentCode = null, PayrollComponentType? componentType = null, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollEmployeeComponentExceptionDto>> SaveEmployeeComponentExceptionsAsync(Guid tenantId, PayrollEmployeeComponentExceptionBulkSaveDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollPromotionArrearsEntryDto>> GetPromotionArrearsAsync(Guid tenantId, string? employeeNumber = null, bool includeInactive = false, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollPromotionArrearsEntryDto>> SavePromotionArrearsAsync(Guid tenantId, PayrollPromotionArrearsBulkSaveDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollOvertimeSummaryEntryDto>> GetOvertimeSummariesAsync(Guid tenantId, string? employeeNumber = null, bool includeInactive = false, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollOvertimeSummaryEntryDto>> SaveOvertimeSummariesAsync(Guid tenantId, PayrollOvertimeSummaryBulkSaveDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollContributionOpeningBalanceDto>> GetContributionOpeningBalancesAsync(Guid tenantId, string? contributionCode = null, string? contributionCodeType = null, bool includeInactive = false, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollContributionOpeningBalanceDto>> SaveContributionOpeningBalancesAsync(Guid tenantId, PayrollContributionOpeningBalanceBulkSaveDto dto, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollContributionTransactionDto>> GetContributionTransactionsAsync(Guid tenantId, string? employeeNumber = null, string? contributionCode = null, string? contributionCodeType = null, bool includeInactive = false, CancellationToken cancellationToken = default);
    Task<PayrollContributionTransactionDto> UpsertContributionTransactionAsync(Guid tenantId, UpsertPayrollContributionTransactionDto dto, CancellationToken cancellationToken = default);
    Task<PayrollImportBatchDto> ImportEmployeeReconciliationAsync(Guid tenantId, Guid? importedByUserId, PayrollReconciliationImportDto dto, CancellationToken cancellationToken = default);
    Task<PayrollImportBatchDto?> GetImportBatchAsync(Guid tenantId, Guid batchId, CancellationToken cancellationToken = default);

    Task<IReadOnlyList<PayrollRunDto>> GetRunsAsync(Guid tenantId, CancellationToken cancellationToken = default);
    Task<PayrollRunDto?> GetRunAsync(Guid tenantId, Guid runId, CancellationToken cancellationToken = default);
    Task<PayrollRunDto> CreateRunAsync(Guid tenantId, CreatePayrollRunDto dto, CancellationToken cancellationToken = default);
    Task<PayrollRunDto> CalculateRunAsync(Guid tenantId, Guid runId, Guid? userId, CancellationToken cancellationToken = default);
    Task<PayrollRunDto> SubmitRunForReviewAsync(Guid tenantId, Guid runId, Guid? userId, PayrollRunActionDto dto, CancellationToken cancellationToken = default);
    Task<PayrollRunDto> ApproveRunAsync(Guid tenantId, Guid runId, Guid? userId, PayrollRunActionDto dto, CancellationToken cancellationToken = default);
    Task<PayrollRunDto> CloseRunAsync(Guid tenantId, Guid runId, Guid? userId, PayrollRunActionDto dto, CancellationToken cancellationToken = default);
    Task<PayrollRunDto> RollbackRunAsync(Guid tenantId, Guid runId, Guid? userId, PayrollRunActionDto dto, CancellationToken cancellationToken = default);
    Task<PayrollSummaryReportDto> GetRunSummaryReportAsync(Guid tenantId, Guid runId, Guid? userId, bool createSnapshot = false, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollPayslipDto>> GetPayslipsAsync(Guid tenantId, Guid runId, Guid? employeeId = null, string? categoryType = null, string? categoryValue = null, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<PayrollPayslipSnapshotDto>> GeneratePayslipSnapshotsAsync(Guid tenantId, Guid runId, Guid? userId, CancellationToken cancellationToken = default);
    Task<PayrollPayslipEmailResultDto> EmailPayslipsAsync(Guid tenantId, Guid runId, Guid? userId, PayrollPayslipEmailRequestDto dto, CancellationToken cancellationToken = default);
    Task<PayrollJournalPostingDto> PostPayrollJournalAsync(Guid tenantId, Guid runId, Guid? userId, PayrollRunActionDto dto, CancellationToken cancellationToken = default);
}
