// <auto-generated />
using ErpSystem.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ErpSystem.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260802171742_TDC0613InventoryValuationReconciliation")]
partial class TDC0613InventoryValuationReconciliation
{
}
