using ErpSystem.Core.Interfaces.Estate;

namespace ErpSystem.Core.Services.Estate;

public sealed class EstateProcedureCatalogService : IEstateProcedureCatalogService
{
    public IReadOnlyList<EstateProcedureCatalogItem> GetProcedures() =>
    [
        new("Secretarial and Estates Registry", "EstateRegistrySecretariat", "Source: Estate - Estates Operational Manual", "Incoming files, letters, forms purchase, file dispatch, movement tracing, typing, client updates, and departmental registry controls routed through configured workflows.", "ClipboardList", 0, "slate", "Operational Queue"),
        new("Estate Records Management", "EstateRecordsManagement", "Source: Estate - Estates Operational Manual", "Estate registers, HOS ledger cards, record updates, transfer amendments, agency notifications, and building permit ownership verification routed through configured workflows.", "Database", 0, "indigo", "Register"),
        new("Land and Landed Property Inspection", "EstateInspection", "Source: Estate - Estates Operational Manual", "Site inspection, site report preparation, neighbourhood details, current development capture, and photographic evidence routed through configured workflows.", "MapPin", 0, "teal", "Event Workflow"),
        new("Search Application", "EstateSearchApplication", "Source: Estate - Estates Operational Manual", "Search request intake, ground-rent arrears control, property-file review, and search report preparation routed through configured workflows.", "Search", 0, "sky"),
        new("Change of Address and Record Amendment", "EstateRecordAmendment", "Source: Estate - Estates Operational Manual", "Address updates, statutory declaration support, arrears checks, and Revenue and Estate Records amendment routing through configured workflows.", "FilePenLine", 0, "cyan"),
        new("Certified True Copies", "EstateCertifiedTrueCopy", "Source: Estate - Estates Operational Manual", "Certified copy request, arrears verification, fee/payment confirmation, document preparation, and certification routing through configured workflows.", "FileCheck2", 0, "emerald"),
        new("Joint Ownership / Addition of Name", "EstateJointOwnership", "Source: Estate - Estates Operational Manual", "Additional-name requests, lease checks, cadastral plan routing, deed of variation, registration, detachment, and records amendment through configured workflows.", "Users", 0, "violet"),
        new("Transfer / Portion Transfer of Plot", "EstateTransfer", "Source: Estate - Estates Operational Manual", "Transfer request processing, fee calculation, HOE and MD approval, Legal routing, completion, and records amendment through configured workflows.", "ArrowRightLeft", 0, "blue"),
        new("Assignment", "EstateAssignment", "Source: Estate - Estates Operational Manual", "Consent to assign, draft deed review, arrears and development checks, Legal routing, registration, detachment, and completion notices through configured workflows.", "FileSignature", 0, "purple"),
        new("Consent to Mortgage / Mortgage in Principle", "EstateMortgageConsent", "Source: Estate - Estates Operational Manual", "Mortgage consent intake, arrears and development checks, draft deed or mortgage-in-principle review, approval, Legal routing, and dispatch through configured workflows.", "ShieldCheck", 0, "zinc"),
        new("Lease Preparation", "EstateLeasePreparation", "Source: Estate - Estates Operational Manual", "Lease request processing, substantial development checks, cadastral requirements, invoice/payment routing, Legal preparation, and records update through configured workflows.", "FileText", 0, "amber"),
        new("Additional Land Application", "EstateAdditionalLand", "Source: Estate - Estates Operational Manual", "Additional land request intake, adjoining plot verification, inspection, availability review, fee recommendation, approval, offer, and records update through configured workflows.", "SquarePlus", 0, "teal"),
        new("Revision of Layout", "EstateLayoutRevision", "Source: Estate - Estates Operational Manual", "Layout revision request review, planning and site implications, MD approval letter, dispatch, and records update through configured workflows.", "LayoutPanelTop", 0, "cyan"),
        new("Change of Land Use", "EstateChangeOfUse", "Source: Estate - Estates Operational Manual", "Change-of-use request processing, planning/site checks, change-of-use fee calculation, approval, dispatch, and records update through configured workflows.", "RefreshCw", 0, "sky"),
        new("Reminder and Rate Revision Notices", "EstateReminderRateRevision", "Source: Estate - Estates Operational Manual", "Quarterly proposal reminders, rate revision notices, unpaid proposal sorting, approval/signature, dispatch, and follow-up tracking through configured workflows.", "BellRing", 0, "red", "Operational Queue"),
        new("Lease Surrender and Renewal", "EstateLeaseRenewal", "Source: Estate - Estates Operational Manual", "Renewal requirements, surrender option processing, term threshold checks, committee review, invoicing, approval, and lease renewal close-out through configured workflows.", "RefreshCw", 0, "lime"),
        new("Serviced Plots and HOS Allocation", "EstateServicedPlotAllocation", "Source: Estate - Estates Operational Manual", "HOS unit allocation, serviced plot allocation, payment book updates, Offer Letters, Right of Entry letters, and quarterly reporting through configured workflows.", "Landmark", 0, "green"),
        new("Lands / Partially Serviced Schedule", "EstateLandsPartiallyServiced", "Source: Estate - Estates Operational Manual", "Application intake, proposal letters, Land Management Fee and ground rent determination, Offer and Right of Entry preparation, and reports through configured workflows.", "Home", 0, "orange"),
        new("Housing and Home Ownership Scheme", "EstateHousingHomeOwnership", "Source: Estate - Estates Questionnaire Response", "Recognition of tenancy, rental-to-HOS conversion, purchase completion, Offer Letter preparation, lease request, and records update through configured workflows.", "Building2", 0, "rose"),
        new("Traditional Lands", "EstateTraditionalLands", "Source: Estate - Estates Operational Manual", "Traditional lands proposal processing, fee determination, allocation review, Offer and Right of Entry preparation, and quarterly reporting through configured workflows.", "Trees", 0, "emerald"),
        new("Tenancy Regularisation", "EstateTenancyRegularisation", "Source: Estate - Estates Operational Manual", "Regularisation communities, tenancy validation, documentation, fee/payment checks, approvals, and records amendment through configured workflows.", "BadgeCheck", 0, "yellow"),
        new("Estate Reporting and SOP Controls", "EstateReportingControls", "Source: Estate - Estates Operational Manual", "Quarterly productivity reports, rent rolls, debtor lists, allocation revenue reports, transfer and assignment returns, lease and mortgage reports, Board summaries, appendix fee controls, and SOP audit evidence routed through configured workflows.", "BarChart3", 0, "fuchsia", "Dashboard / Report")
    ];
}
