using ErpSystem.Core.Interfaces.Workflow;

namespace ErpSystem.Core.Services.Workflow;

public sealed class WorkflowEntityTypeCatalogService : IWorkflowEntityTypeCatalogService
{
    public IReadOnlyList<WorkflowEntityTypeCatalogItem> GetDefaultEntityTypes()
    {
        var defaults = new List<WorkflowEntityTypeCatalogItem>
        {
            new("WorkOrder", "Maintenance", "Maintenance work orders", "Settings", "#3B82F6", 10),
            new("JobCard", "Maintenance", "Maintenance job cards", "FileText", "#8B5CF6", 20),
            new("FleetTrip", "Maintenance", "Fleet trip requests and dispatch", "MapPin", "#0EA5E9", 25),
            new("FleetTripInspection", "Maintenance", "Fleet pre-start, post-trip, inspection, and service sheet approvals", "ClipboardCheck", "#14B8A6", 26),
            new("PurchaseOrder", "Procurement", "Procurement purchase orders", "FileText", "#F59E0B", 30),
            new("ProcurementPlan", "Procurement", "Annual, quarterly, and amended procurement plans", "ClipboardList", "#2563EB", 35),
            new("PurchaseRequisition", "Procurement", "Procurement requisitions", "FileText", "#F97316", 40),
            new("Tender", "Procurement", "Procurement tenders (RFQ/RFP/ITB/EOI)", "FileText", "#06B6D4", 45),
            new("RFQ", "Procurement", "Requests for Quotation (RFQs)", "FileText", "#06B6D4", 46),
            new("SupplierQuote", "Procurement", "Supplier quotes submitted in response to RFQs", "FileText", "#22C55E", 47),
            new("Bid", "Procurement", "Supplier bids submitted in response to tenders", "FileText", "#22C55E", 48),
            new("Evaluation", "Procurement", "Tender evaluations and scoring", "CheckCircle", "#F59E0B", 49),
            new("Asset", "Inventory", "Assets and equipment", "Database", "#10B981", 50),
            new("Inventory", "Inventory", "Inventory records", "Database", "#14B8A6", 60),
            new("InventoryTransfer", "Inventory", "Inventory transfers", "Truck", "#A855F7", 65),
            new("PurchaseReturn", "Inventory", "Supplier returns from accepted stock receipts", "PackageMinus", "#B45309", 66),
            new("InventoryRequisition", "Inventory", "Inventory requisitions", "ClipboardList", "#0EA5E9", 68),
            new("Employee", "Human Resources", "Human resources employees", "Users", "#6366F1", 70),
            new("PayrollRun", "Human Resources", "HR payroll runs, payslip generation, and posting", "WalletCards", "#0EA5E9", 72),
            new("PayrollPayslipEmail", "Human Resources", "HR payroll payslip email notifications", "Mail", "#2563EB", 73),
            new("PayrollSalaryAdvance", "Human Resources", "HR payroll salary advance requests", "ReceiptText", "#14B8A6", 74),
            new("PayrollBonusSetup", "Human Resources", "HR payroll bonus setup and exception approval", "BadgePercent", "#F97316", 76),
            new("PayrollBackpaySetup", "Human Resources", "HR payroll salary back pay and salary increase setup", "TrendingUp", "#22C55E", 78),
            new("LeaveRequest", "Human Resources", "HR leave requests and approvals", "CalendarDays", "#0EA5E9", 79),
            new("LeavePlan", "Human Resources", "HR annual leave plans and plan approvals", "CalendarRange", "#6366F1", 79),
            new("LeaveEncashment", "Human Resources", "HR leave encashment requests and approvals", "Banknote", "#22C55E", 79),
            new("TrainingNomination", "Human Resources", "HR training nominations and approvals", "GraduationCap", "#A855F7", 79),
            new("StaffAttendanceRegularization", "Human Resources", "HR attendance regularization requests and approvals", "ClockAlert", "#F59E0B", 79),
            new("StaffOvertimeRequest", "Human Resources", "HR overtime pre-approval requests", "Timer", "#EF4444", 79),
            new("RemoteWorkRequest", "Human Resources", "HR remote and work-from-home requests", "House", "#8B5CF6", 79),
            new("ConsultantTimesheet", "Human Resources", "Consultant timesheet submission and approval", "FileClock", "#0D9488", 79),
            new("AppraisalTemplate", "Human Resources", "HR appraisal form templates submitted for HR sign-off", "ClipboardCheck", "#7C3AED", 79),
            new("SalaryReviewProposal", "Human Resources", "Merit increase and bonus proposals raised from appraisal outcomes", "BadgeDollarSign", "#16A34A", 79),
            new("EmploymentActionProposal", "Human Resources", "Promotion, demotion, renewal, termination and recognition proposals from appraisal outcomes", "UserCog", "#DC2626", 79),
            new("PerformanceImprovementPlan", "Human Resources", "Performance improvement plans approved before they are served on the employee", "ClipboardList", "#EA580C", 79),
            new("StaffRequisition", "Human Resources", "Headcount requisitions approved before a vacancy is opened for recruitment", "UserPlus", "#0891B2", 79),
            new("JobOffer", "Human Resources", "Employment offers approved before they are issued to a candidate", "FileSignature", "#0284C7", 79),
            new("StaffMovement", "Human Resources", "Promotions, transfers, demotions, secondments and acting appointments approved before they take effect", "ArrowRightLeft", "#9333EA", 79),
            new("StaffDisciplinaryAction", "Human Resources", "Disciplinary decisions confirmed before the sanction takes effect", "Gavel", "#DC2626", 79),
            new("EmployeeSeparation", "Human Resources", "Exits signed before clearance begins — resignation, retirement, contract expiry, redundancy, dismissal or death (FR-HR-092)", "DoorOpen", "#B45309", 79),
            new("StaffTravelRequest", "Human Resources", "Staff travel requests approved before flights, hotels or advances are committed", "Plane", "#0EA5E9", 79),
            new("SuccessionPlan", "Human Resources", "Succession plans approved before anyone is named as the intended successor to a post", "Network", "#7C3AED", 79),
            new("ProbationPeriod", "Human Resources", "Probation confirmed by the named confirming authority before HR issues the confirmation letter", "UserCheck", "#059669", 79),
            new("JobDescription", "Human Resources", "Job descriptions approved against a position before they take effect (FR-HR-134)", "FileText", "#0D9488", 79),
            new("ManpowerBudget", "Human Resources", "Manpower budgets approved Department Head to HR to Managing Director before headcount is authorised (FR-HR-135)", "Users", "#B45309", 79),
            // ⚠ Prefixed `Hr`, and deliberately. `AssetTransfer` already means Finance's fixed-asset
            // transfer to WorkflowEntityDisplayService, and `Asset` above is the Inventory one. HR's
            // staff-asset records are a third thing with the same names — see the build plan §3.3.
            new("HrAssetRequisition", "Human Resources", "Staff requests for a company asset, approved before HR issues one (AST-6)", "ClipboardList", "#0891B2", 79),
            new("HrAssetTransfer", "Human Resources", "Company assets moved between employees, locations or units, approved before the move (AST-2)", "ArrowRightLeft", "#7C3AED", 79),
            new("HrAssetSurcharge", "Human Resources", "Charges raised against an employee for a company asset damaged, lost or not returned (AST-3)", "Receipt", "#B45309", 79),
            // ⚠ Prefixed `Hr` for the same reason as the asset types above: the entity-type
            // namespace is flat and shared, and `Objective` / `TermsOfReference` are phrases other
            // modules could plausibly claim. Round 2, lane F3.
            new("HrTeamTermsOfReference", "Human Resources", "A committee's charter — what it may decide and on whose authority — approved before the committee operates under it", "ScrollText", "#0D9488", 79),
            new("HrTeamObjective", "Human Resources", "What a team or committee undertakes to deliver in a period, approved before work starts against it", "Target", "#7C3AED", 79),
            // Round 3, lane S. `Hr`-prefixed like the types above — the namespace is flat and shared.
            new("HrEmployeeSalaryChangeRequest", "Human Resources", "A change to an employee's pay — grade placement, negotiated amount or pay basis — applied to HR and payroll when approved", "BadgeDollarSign", "#0F766E", 79),
            new("Project", "Projects", "Project management items", "CheckCircle", "#22C55E", 80),
            new("ProjectDeliverable", "Projects", "Project deliverable approvals and external sign-off", "PackageCheck", "#16A34A", 82),
            new("ProjectClosure", "Projects", "Project closure approval and close-out governance", "Flag", "#15803D", 84),
            new("CentralDocumentRegister", "Document Management", "Central DMS document register workflows", "FileText", "#475569", 85),
            new("CentralDocumentMetadataTemplate", "Document Management", "Central DMS metadata template workflows", "BookTemplate", "#0891B2", 86),
            new("CentralDocumentVersion", "Document Management", "Central DMS version and revision control workflows", "GitBranch", "#7C3AED", 87),
            new("CentralDocumentAnnotation", "Document Management", "Central DMS Syncfusion annotation and comment review workflows", "MessageSquare", "#B45309", 88),
            new("CentralDocumentGovernance", "Document Management", "Central DMS access, retention, and audit governance workflows", "ShieldCheck", "#059669", 89),
            new("CentralDocumentIntegrationQueue", "Document Management", "Central DMS module integration queue workflows", "Workflow", "#4F46E5", 90),
            new("Customer", "Sales", "Sales customers", "User", "#0EA5E9", 90),
            new("SalesOrder", "Sales", "Sales orders and customer sales transactions", "ShoppingCart", "#2563EB", 91),
            new("SalesAgreement", "Sales", "Sales, lease, tenancy, and plot allocation agreements", "FileText", "#7C3AED", 92),
            new("SalesAllocation", "Sales", "Sales reservations, plot allocations, and saleable source holds", "MapPinned", "#0891B2", 93),
            new("LandAcquisition", "Estate", "Estate land acquisition procedure and statutory registration approvals", "Landmark", "#0F766E", 94),
            new("EstatePropertyManagementPropertyUnit", "Estate", "Estate property management property, site, unit, and space receiving workflows", "Building2", "#0F766E", 95),
            new("EstatePropertyManagementLease", "Estate", "Estate property management lease operations workflows", "FileSignature", "#0284C7", 96),
            new("EstatePropertyManagementTenantOccupant", "Estate", "Estate property management tenant and occupant operations workflows", "Users", "#0891B2", 97),
            new("EstatePropertyManagementBillingServiceCharge", "Estate", "Estate property management billing and service charge operations workflows", "CreditCard", "#B45309", 98),
            new("EstatePropertyManagementGroundRent", "Estate", "Estate property management land-only ground rent setup, assessment, review, and billing readiness workflows", "Banknote", "#059669", 98),
            new("EstatePropertyManagementListingApplication", "Estate", "Estate property listing purchase bids and rental application workflows", "ClipboardList", "#4F46E5", 99),
            new("EstatePropertyManagementOccupancyAvailability", "Estate", "Estate property management occupancy and availability operations workflows", "Home", "#059669", 99),
            new("EstatePropertyManagementMoveInMoveOutHandover", "Estate", "Estate property management move-in, move-out, and handover operations workflows", "KeyRound", "#7C3AED", 100),
            new("EstatePropertyManagementDocumentRecordIndex", "Estate", "Estate property management document and records index workflows", "FileText", "#65A30D", 101),
            new("EstateFacilityPropertySite", "Estate", "Estate facilities property and site operating view workflows", "Building2", "#0F766E", 96),
            new("EstateFacilityLease", "Estate", "Estate facilities lease and occupancy coordination workflows", "FileCheck", "#0284C7", 96),
            new("EstateFacilityMaintenance", "Estate", "Estate facilities maintenance request, inspection, and closure workflows", "Wrench", "#B45309", 97),
            new("EstateFacilityComplaint", "Estate", "Estate facilities complaint, escalation, and resolution workflows", "MessageSquare", "#E11D48", 98),
            new("EstateFacilityServiceProvider", "Estate", "Estate facilities service provider contract, assignment, and performance workflows", "Briefcase", "#7C3AED", 99),
            new("EstateFacilityStaffCleaner", "Estate", "Estate facilities staff and cleaner assignment and supervision workflows", "ClipboardCheck", "#059669", 100),
            new("EstateFacilityAssetRegister", "Estate", "Estate facilities asset operating view workflows", "Database", "#4F46E5", 101),
            new("EstateFacilityDocument", "Estate", "Estate facilities document index and DMS readiness workflows", "FileText", "#65A30D", 102),
            new("EstateRegistrySecretariat", "Estate", "Estate registry, secretarial intake, file movement, and client update workflows", "ClipboardList", "#334155", 103),
            new("EstateRecordsManagement", "Estate", "Estate records, registers, ledgers, amendments, and verification workflows", "Database", "#4F46E5", 104),
            new("EstateInspection", "Estate", "Land and landed-property inspection and site report workflows", "MapPin", "#0F766E", 105),
            new("EstateSearchApplication", "Estate", "Estate search application and search report workflows", "Search", "#0284C7", 106),
            new("EstateRecordAmendment", "Estate", "Estate change of address and record amendment workflows", "FilePenLine", "#0891B2", 107),
            new("EstateCertifiedTrueCopy", "Estate", "Certified true copy request and certification workflows", "FileCheck2", "#059669", 108),
            new("EstateJointOwnership", "Estate", "Joint ownership and addition-of-name workflows", "Users", "#7C3AED", 109),
            new("EstateTransfer", "Estate", "Transfer and portion-transfer of plot workflows", "ArrowRightLeft", "#2563EB", 110),
            new("EstateAssignment", "Estate", "Assignment consent, registration, and completion workflows", "FileSignature", "#6D28D9", 111),
            new("EstateMortgageConsent", "Estate", "Consent to mortgage and mortgage-in-principle workflows", "ShieldCheck", "#52525B", 112),
            new("EstateLeasePreparation", "Estate", "Lease preparation, cadastral, invoice, and legal routing workflows", "FileText", "#B45309", 113),
            new("EstateAdditionalLand", "Estate", "Additional land application workflows", "SquarePlus", "#0F766E", 114),
            new("EstateLayoutRevision", "Estate", "Layout revision workflows", "LayoutPanelTop", "#0891B2", 115),
            new("EstateChangeOfUse", "Estate", "Change of land use workflows", "RefreshCw", "#0284C7", 116),
            new("EstateReminderRateRevision", "Estate", "Reminder and rate revision notice workflows", "BellRing", "#DC2626", 117),
            new("EstateLeaseRenewal", "Estate", "Lease surrender and renewal workflows", "RefreshCw", "#65A30D", 118),
            new("EstateServicedPlotAllocation", "Estate", "Serviced plot and HOS allocation workflows", "Landmark", "#16A34A", 119),
            new("EstateLandsPartiallyServiced", "Estate", "Lands and partially serviced schedule workflows", "Home", "#EA580C", 120),
            new("EstateHousingHomeOwnership", "Estate", "Housing, tenancy recognition, and home ownership scheme workflows", "Building2", "#E11D48", 121),
            new("EstateTraditionalLands", "Estate", "Traditional lands proposal and allocation workflows", "Trees", "#059669", 122),
            new("EstateTenancyRegularisation", "Estate", "Tenancy regularisation workflows", "BadgeCheck", "#CA8A04", 123),
            new("EstateReportingControls", "Estate", "Estate reporting, approvals, audit trail, and control workflows", "BarChart3", "#C026D3", 124),
            new("Refund", "Sales", "Customer refund requests and approvals", "RotateCcw", "#F97316", 95),
            new("CreditNote", "Sales", "Customer credit notes and adjustments", "ReceiptText", "#14B8A6", 96),
            new("BusinessPartner", "Procurement", "Business partner onboarding/approvals (suppliers/contractors/customers)", "Building", "#64748B", 100),
            new("Vendor", "Procurement", "Business partners and vendors", "Building", "#64748B", 105),
            new("Quality", "Quality", "Quality inspections", "CheckCircle", "#EF4444", 110),
            new("ServiceRequest", "Helpdesk", "Service catalog requests", "ClipboardList", "#10B981", 115),
            new("LegalProcedure", "Legal", "Legal department procedure manual workflows", "Gavel", "#334155", 120),
            new("LegalOpinionAdvisory", "Legal", "Legal opinion and advisory request workflows", "MessageSquare", "#4F46E5", 120),
            new("LegalExternalCounsel", "Legal", "External counsel instruction, fee, and performance workflows", "Briefcase", "#52525B", 120),
            new("LegalMortgage", "Legal", "Mortgage review, preparation, and approval workflows", "FileSignature", "#475569", 121),
            new("LegalMortgageInPrinciple", "Legal", "Mortgage in principle review and approval workflows", "FileCheck", "#64748B", 122),
            new("LegalCourtProcess", "Legal", "Court process review, filing, hearing, and follow-up workflows", "Scale", "#7C3AED", 123),
            new("LegalOtherCourtProcess", "Legal", "Other court process review and action workflows", "Scale", "#6D28D9", 124),
            new("LegalTerminationRecognition", "Legal", "Termination and recognition procedure workflows", "FileX", "#B45309", 125),
            new("LegalAssignmentSubleaseVesting", "Legal", "Assignment, sublease, and vesting procedure workflows", "FileText", "#0F766E", 126),
            new("LegalLeaseVariationRenewalSublease", "Legal", "Lease, deed of variation, renewal, and sublease procedure workflows", "FileText", "#0891B2", 127),
            new("LegalTransfer", "Legal", "Transfer procedure review and approval workflows", "ArrowRightLeft", "#2563EB", 128),
            new("PlanningLandAllocationVetting", "Planning", "Planning land allocation and temporary license vetting workflows", "ClipboardCheck", "#0F766E", 129),
            new("PlanningChangeOfUseReview", "Planning", "Planning change of use review workflows", "RefreshCw", "#0284C7", 130),
            new("PlanningSchemeLayoutPreparation", "Planning", "Planning scheme and layout preparation workflows", "Map", "#4F46E5", 131),
            new("PlanningSiteReport", "Planning", "Planning site report inspection workflows", "MapPin", "#059669", 132),
            new("PlanningSitePlanPreparation", "Planning", "Planning site plan preparation workflows", "FileText", "#2563EB", 133),
            new("PlanningOfficialSearchData", "Planning", "Planning official search and land use data workflows", "Search", "#0891B2", 134),
            new("PlanningDevelopmentPermitConformity", "Planning", "Development permit conformity review workflows", "FileCheck2", "#7C3AED", 135),
            new("PlanningRegularization", "Planning", "Planning regularization workflows for unplanned or informal occupation", "BadgeCheck", "#B45309", 136),
            new("PlanningLayoutReviewCorrection", "Planning", "Planning layout review and correction workflows", "FilePenLine", "#EA580C", 137),
            new("PlanningComplianceInspection", "Planning", "Planning compliance site inspection and reporting workflows", "ClipboardList", "#E11D48", 138),
            new("PlanningDisputeComplaint", "Planning", "Planning dispute resolution and client complaint workflows", "MessageSquare", "#6D28D9", 139),
            new("PlanningAssemblySpatialCommittee", "Planning", "District assembly spatial planning committee meeting workflows", "Users", "#334155", 140)
        };

        return defaults
            .Select((item, index) => item with { DisplayOrder = item.DisplayOrder == 0 ? (index + 1) * 10 : item.DisplayOrder })
            .ToList();
    }
}
