'use client';
import * as React from 'react';
import { CheckCircle, RefreshCw, XCircle } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { workflowApiService } from '@/services/workflow-api.service';
import { PWAManager } from '@/lib/pwa';

const queueKey='workflow-offline-actions-v1';
export default function WorkflowInboxPage(){const [items,setItems]=React.useState<any[]>([]);const [selected,setSelected]=React.useState<any>();const [action,setAction]=React.useState<'approve'|'reject'>('approve');const [comments,setComments]=React.useState('');const [syncing,setSyncing]=React.useState(false);
const load=React.useCallback(async()=>{try{setItems(await workflowApiService.getMobileWorkflowInbox());}catch(error:any){if(navigator.onLine)toast.error(error?.message||'Inbox unavailable');}},[]);
const sync=React.useCallback(async()=>{if(!navigator.onLine)return;const queued=JSON.parse(localStorage.getItem(queueKey)||'[]');if(!queued.length)return;setSyncing(true);const remaining=[];for(const item of queued){try{const result=await workflowApiService.submitOfflineWorkflowAction(item);if(result?.status===3)remaining.push(item);}catch{remaining.push(item);}}localStorage.setItem(queueKey,JSON.stringify(remaining));setSyncing(false);await load();},[load]);
React.useEffect(()=>{void load();void sync();const online=()=>void sync();window.addEventListener('online',online);return()=>window.removeEventListener('online',online);},[load,sync]);
const submit=async()=>{if(!selected)return;const request={idempotencyKey:crypto.randomUUID(),actionType:action,payload:{stepInstanceId:selected.stepInstanceId,comments}};if(!navigator.onLine){const queue=JSON.parse(localStorage.getItem(queueKey)||'[]');queue.push(request);localStorage.setItem(queueKey,JSON.stringify(queue));toast.success('Action queued');setSelected(undefined);return;}try{const result=await workflowApiService.submitOfflineWorkflowAction(request);if(result?.status===3)throw new Error(result.error);toast.success('Workflow updated');setSelected(undefined);await load();}catch(error:any){toast.error(error?.message||'Action failed');}};
const enablePush=async()=>{const permission=await PWAManager.getInstance().requestNotificationPermission();if(permission!=='granted')return;const subscription=await PWAManager.getInstance().subscribeToNotifications();if(subscription){await workflowApiService.subscribeWorkflowPush(subscription);toast.success('Notifications enabled');}};
return <div className="mx-auto max-w-3xl space-y-4 p-4"><div className="flex items-center justify-between"><h1 className="text-xl font-semibold">Approval inbox</h1><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>void enablePush()}>Enable notifications</Button><Button size="icon" variant="outline" title="Sync" onClick={()=>void sync()} disabled={syncing}><RefreshCw className={`h-4 w-4 ${syncing?'animate-spin':''}`}/></Button></div></div>
<div className="divide-y rounded-md border bg-background">{items.map(item=><div key={item.id} className="space-y-3 p-4"><div className="flex items-start justify-between"><div><div className="font-medium">{item.step}</div><div className="text-sm text-muted-foreground">{item.entityId}</div></div>{item.dueDate&&<Badge variant={new Date(item.dueDate)<new Date()?'destructive':'outline'}>{new Date(item.dueDate).toLocaleDateString()}</Badge>}</div><div className="flex gap-2"><Button size="sm" onClick={()=>{setSelected(item);setAction('approve')}}><CheckCircle className="mr-2 h-4 w-4"/>Approve</Button><Button size="sm" variant="outline" onClick={()=>{setSelected(item);setAction('reject')}}><XCircle className="mr-2 h-4 w-4"/>Reject</Button></div></div>)}</div>
<Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(undefined)}}><DialogContent><DialogHeader><DialogTitle>{action==='approve'?'Approve':'Reject'}</DialogTitle></DialogHeader><Textarea value={comments} onChange={event=>setComments(event.target.value)} placeholder="Comments"/><DialogFooter><Button variant="outline" onClick={()=>setSelected(undefined)}>Cancel</Button><Button variant={action==='reject'?'destructive':'default'} onClick={()=>void submit()} disabled={action==='reject'&&!comments.trim()}>Confirm</Button></DialogFooter></DialogContent></Dialog></div>}
