using System.Globalization;
using System.Text.RegularExpressions;
using ClosedXML.Excel;
using ErpSystem.Core.DTOs.HR;
using ErpSystem.Core.Enums;

namespace ErpSystem.Api.Services.HR.EmployeeImport;

public sealed class EmployeeImportParsedRow
{
    public int RowNumber { get; init; }
    public Dictionary<string, string?> Raw { get; } = new();
    public List<EmployeeImportFindingDto> Findings { get; } = new();
    public EmployeeImportResolvedRow? Resolved { get; set; }
    public string? StaffNumber { get; set; }
    public string? DisplayName { get; set; }
    public EmploymentType? EmploymentType { get; set; }
    public int? ManagerRowNumber { get; set; }

    public int ErrorCount => Findings.Count(f => f.Severity == EmployeeImportFindingSeverity.Error);
    public int WarningCount => Findings.Count(f => f.Severity == EmployeeImportFindingSeverity.Warning);

    public EmployeeImportRowOutcome Outcome =>
        ErrorCount > 0 ? EmployeeImportRowOutcome.Error
        : WarningCount > 0 ? EmployeeImportRowOutcome.Warning
        : EmployeeImportRowOutcome.Ready;
}

public sealed class EmployeeImportParseResult
{
    public int TemplateVersion { get; set; }
    public List<EmployeeImportFindingDto> FileFindings { get; } = new();
    public List<EmployeeImportParsedRow> Rows { get; } = new();
    public bool FileRejected => FileFindings.Any(f => f.Severity == EmployeeImportFindingSeverity.Error);
}

/// <summary>
/// Reads an uploaded template and turns every data row into the payload it would become, with a
/// finding for everything that is wrong or worth a look. Nothing here touches the database: the
/// reference data arrives loaded, so the same code checks a 10-row file and a 10,000-row one.
/// </summary>
/// <remarks>
/// The rules are the ones in <c>docs/HR/HR-EMPLOYEE-IMPORT-DESIGN.md</c> §5. Error means the row will
/// not be written; Warning means it will, and the person is listed for follow-up.
/// </remarks>
public static class EmployeeImportWorkbookReader
{
    private static readonly Regex EmailRegex = new(@"^[^@\s]+@[^@\s]+\.[^@\s]+$", RegexOptions.Compiled | RegexOptions.IgnoreCase);
    private static readonly Regex PhoneRegex = new(@"^\+?[0-9][0-9\s\-()]{5,}$", RegexOptions.Compiled);

    public static EmployeeImportParseResult Read(
        Stream stream, EmployeeImportReferenceData refs, IReadOnlyList<EmployeeImportColumn> columns)
    {
        var result = new EmployeeImportParseResult();

        XLWorkbook workbook;
        try
        {
            workbook = new XLWorkbook(stream);
        }
        catch (Exception ex)
        {
            result.FileFindings.Add(Error(null, null,
                "The file is not a readable .xlsx workbook. Save it from Excel as 'Excel Workbook (*.xlsx)' and try again. " + ex.Message));
            return result;
        }

        using (workbook)
        {
            // ── 1. The stamp ──
            var idBindings = new Dictionary<string, (Guid TypeId, bool IsExpiry)>();
            if (!workbook.Worksheets.TryGetWorksheet(EmployeeImportColumns.MetaSheet, out var meta))
            {
                result.FileFindings.Add(Error(null, null,
                    "This workbook was not generated by the system (the hidden _meta sheet is missing). Download the template from HR → Employees → Import and enter the data there."));
                return result;
            }

            var lastMetaRow = meta.LastRowUsed()?.RowNumber() ?? 0;
            for (var r = 1; r <= lastMetaRow; r++)
            {
                var key = ReadText(meta.Cell(r, 1));
                if (key == null) continue;
                switch (key)
                {
                    case "TemplateVersion":
                        result.TemplateVersion = int.TryParse(ReadText(meta.Cell(r, 2)), out var v) ? v : 0;
                        break;
                    case "IdColumn":
                        var header = EmployeeImportColumns.NormalizeHeader(ReadText(meta.Cell(r, 2)));
                        var isExpiry = string.Equals(ReadText(meta.Cell(r, 4)), "Expiry", StringComparison.OrdinalIgnoreCase);
                        if (header.Length > 0 && Guid.TryParseExact(ReadText(meta.Cell(r, 3)), "N", out var typeId))
                            idBindings[header] = (typeId, isExpiry);
                        break;
                }
            }

            if (result.TemplateVersion != EmployeeImportColumns.TemplateVersion)
            {
                result.FileFindings.Add(Error(null, null,
                    $"This template is version {result.TemplateVersion}; the system expects version {EmployeeImportColumns.TemplateVersion}. Download a fresh template and move the data across."));
                return result;
            }

            // ── 2. The sheet and its header row ──
            if (!workbook.Worksheets.TryGetWorksheet(EmployeeImportColumns.EmployeesSheet, out var sheet))
            {
                result.FileFindings.Add(Error(null, null, $"The workbook has no '{EmployeeImportColumns.EmployeesSheet}' sheet."));
                return result;
            }

            var lastColumn = sheet.LastColumnUsed()?.ColumnNumber() ?? 0;
            var lastRow = sheet.LastRowUsed()?.RowNumber() ?? 0;
            var byHeader = columns.ToDictionary(c => EmployeeImportColumns.NormalizeHeader(c.Header), c => c);
            var knownTypeIds = refs.IdentificationTypes.ToDictionary(t => t.Id);
            var columnIndex = new Dictionary<string, int>(); // key → excel column
            var ignoredHeaders = new List<string>();

            for (var c = 1; c <= lastColumn; c++)
            {
                var raw = ReadText(sheet.Cell(1, c));
                var header = EmployeeImportColumns.NormalizeHeader(raw);
                if (header.Length == 0) continue;

                if (byHeader.TryGetValue(header, out var column))
                {
                    columnIndex.TryAdd(column.Key, c);
                    continue;
                }

                if (idBindings.TryGetValue(header, out var binding))
                {
                    if (!knownTypeIds.ContainsKey(binding.TypeId))
                    {
                        result.FileFindings.Add(Warning(null, $"{EmployeeImportColumns.EmployeesSheet}!{sheet.Cell(1, c).Address.ColumnLetter}1",
                            $"Column '{raw}' refers to an identification type that no longer exists in the system; it is ignored."));
                        continue;
                    }
                    columnIndex.TryAdd(binding.IsExpiry
                        ? EmployeeImportColumns.IdExpiryKey(binding.TypeId)
                        : EmployeeImportColumns.IdNumberKey(binding.TypeId), c);
                    continue;
                }

                if (header is "RESULT" or "FINDINGS") continue;
                ignoredHeaders.Add(raw!.Trim());
            }

            if (ignoredHeaders.Count > 0)
                result.FileFindings.Add(Warning(null, null,
                    $"Columns not in the template are ignored: {string.Join(", ", ignoredHeaders)}."));

            var missingRequired = columns.Where(c => c.Required && !columnIndex.ContainsKey(c.Key)).Select(c => c.Header).ToList();
            if (missingRequired.Count > 0)
            {
                result.FileFindings.Add(Error(null, null,
                    $"Required columns are missing from the Employees sheet: {string.Join(", ", missingRequired)}. Do not rename or delete template columns."));
                return result;
            }

            var missingOptional = columns.Where(c => !c.Required && !columnIndex.ContainsKey(c.Key)).Select(c => c.Header).ToList();
            if (missingOptional.Count > 0)
                result.FileFindings.Add(Warning(null, null,
                    $"Optional columns are missing and treated as blank: {string.Join(", ", missingOptional)}."));

            // ── 3. Rows ──
            if (lastRow < 2)
            {
                result.FileFindings.Add(Error(null, null, "The Employees sheet has no data rows."));
                return result;
            }
            if (lastRow - 1 > EmployeeImportColumns.MaxDataRows)
            {
                result.FileFindings.Add(Error(null, null,
                    $"The sheet has {lastRow - 1:N0} rows; one import takes at most {EmployeeImportColumns.MaxDataRows:N0}. Split the file."));
                return result;
            }

            var skippedExample = false;
            for (var r = 2; r <= lastRow; r++)
            {
                var row = new EmployeeImportParsedRow { RowNumber = r };
                var anyValue = false;
                foreach (var column in columns)
                {
                    if (!columnIndex.TryGetValue(column.Key, out var c)) { row.Raw[column.Key] = null; continue; }
                    var text = ReadCell(sheet.Cell(r, c), column, row);
                    row.Raw[column.Key] = text;
                    anyValue |= text != null;
                }
                if (!anyValue) continue;

                if (string.Equals(row.Raw.GetValueOrDefault(EmployeeImportColumns.StaffNumber), EmployeeImportColumns.ExampleStaffNumber, StringComparison.OrdinalIgnoreCase))
                {
                    skippedExample = true;
                    continue;
                }

                var cellOf = new Func<string, string?>(key => columnIndex.TryGetValue(key, out var c) ? $"{EmployeeImportColumns.EmployeesSheet}!{sheet.Cell(r, c).Address}" : null);
                ResolveRow(row, refs, columns, cellOf);
                result.Rows.Add(row);
            }

            if (skippedExample)
                result.FileFindings.Add(Warning(null, null, "The example row (EXAMPLE-001) was ignored."));

            if (result.Rows.Count == 0)
            {
                result.FileFindings.Add(Error(null, null, "The Employees sheet has no data rows (only the header and the example)."));
                return result;
            }

            // ── 4. Cross-row checks ──
            CheckInFileDuplicates(result.Rows, columnIndex, sheet);
            ResolveManagers(result.Rows, refs, columnIndex, sheet);
        }

        return result;
    }

    // ── Row resolution ───────────────────────────────────────────────────────────────────────

    private static void ResolveRow(
        EmployeeImportParsedRow row, EmployeeImportReferenceData refs, IReadOnlyList<EmployeeImportColumn> columns,
        Func<string, string?> cellOf)
    {
        var raw = row.Raw;
        string? Get(string key) => raw.GetValueOrDefault(key);
        void Err(string key, string message, List<string>? suggestions = null) =>
            row.Findings.Add(Error(key, cellOf(key), message, suggestions));
        void Warn(string key, string message, List<string>? suggestions = null) =>
            row.Findings.Add(Warning(key, cellOf(key), message, suggestions));

        var resolved = new EmployeeImportResolvedRow();
        var dto = resolved.Employee;

        // Identity
        var staffNumber = Get(EmployeeImportColumns.StaffNumber);
        if (string.IsNullOrWhiteSpace(staffNumber)) Err(EmployeeImportColumns.StaffNumber, "Staff Number is required.");
        else if (staffNumber.Length > 50) Err(EmployeeImportColumns.StaffNumber, "Staff Number is longer than 50 characters.");
        else
        {
            dto.EmployeeNumber = staffNumber;
            row.StaffNumber = staffNumber;
            if (refs.ExistingEmployeeNumbers.ContainsKey(EmployeeImportColumns.NormalizeKey(staffNumber)))
                Err(EmployeeImportColumns.StaffNumber, $"Staff Number '{staffNumber}' already exists in the system (leavers keep their numbers). This import creates new employees only.");
        }

        dto.Title = Text(Get(EmployeeImportColumns.Title), 100, EmployeeImportColumns.Title, Err);
        dto.FirstName = Text(Get(EmployeeImportColumns.FirstName), 100, EmployeeImportColumns.FirstName, Err) ?? string.Empty;
        if (dto.FirstName.Length == 0) Err(EmployeeImportColumns.FirstName, "First Name is required.");
        dto.MiddleName = Text(Get(EmployeeImportColumns.MiddleName), 100, EmployeeImportColumns.MiddleName, Err);
        dto.LastName = Text(Get(EmployeeImportColumns.Surname), 100, EmployeeImportColumns.Surname, Err) ?? string.Empty;
        if (dto.LastName.Length == 0) Err(EmployeeImportColumns.Surname, "Surname is required.");
        row.DisplayName = string.Join(" ", new[] { dto.FirstName, dto.LastName }.Where(s => s.Length > 0));

        // Gender / marital status
        var gender = Get(EmployeeImportColumns.Gender);
        if (string.IsNullOrWhiteSpace(gender)) Err(EmployeeImportColumns.Gender, "Gender is required.");
        else if (EmployeeImportValues.TryParseEnum<Gender>(gender, out var g)) dto.Gender = g;
        else Err(EmployeeImportColumns.Gender, $"Gender '{gender}' is not one of: {string.Join(", ", Enum.GetNames<Gender>())}.");

        var marital = Get(EmployeeImportColumns.MaritalStatus);
        if (!string.IsNullOrWhiteSpace(marital))
        {
            if (EmployeeImportValues.TryParseEnum<MaritalStatus>(marital, out var m)) dto.MaritalStatus = m;
            else Err(EmployeeImportColumns.MaritalStatus, $"Marital Status '{marital}' is not one of: {string.Join(", ", Enum.GetNames<MaritalStatus>())}.");
        }

        // Employment type and dates
        var typeText = Get(EmployeeImportColumns.EmploymentType);
        EmploymentType? employmentType = null;
        if (string.IsNullOrWhiteSpace(typeText)) Err(EmployeeImportColumns.EmploymentType, "Employment Type is required.");
        else if (EmployeeImportValues.TryParseEnum<EmploymentType>(typeText, out var et)) { employmentType = et; dto.EmploymentType = et; }
        else Err(EmployeeImportColumns.EmploymentType, $"Employment Type '{typeText}' is not one of: {string.Join(", ", Enum.GetNames<EmploymentType>())}.");
        row.EmploymentType = employmentType;

        var today = DateOnly.FromDateTime(DateTime.UtcNow);
        var dateEmployed = Date(Get(EmployeeImportColumns.DateEmployed), EmployeeImportColumns.DateEmployed, "Date Employed", Err);
        if (dateEmployed == null && !row.Findings.Any(f => f.Column == EmployeeImportColumns.DateEmployed))
            Err(EmployeeImportColumns.DateEmployed, "Date Employed is required.");
        else if (dateEmployed > today) Err(EmployeeImportColumns.DateEmployed, $"Date Employed {EmployeeImportValues.FormatDate(dateEmployed!.Value)} is in the future.");
        dto.DateEmployed = dateEmployed;

        var dob = Date(Get(EmployeeImportColumns.DateOfBirth), EmployeeImportColumns.DateOfBirth, "Date of Birth", Err);
        if (dob == null && string.IsNullOrWhiteSpace(Get(EmployeeImportColumns.DateOfBirth)))
            Warn(EmployeeImportColumns.DateOfBirth, "Date of Birth is blank.");
        if (dob != null && dateEmployed != null)
        {
            if (dob >= dateEmployed) Err(EmployeeImportColumns.DateOfBirth, "Date of Birth is on or after Date Employed.");
            else
            {
                var age = dateEmployed.Value.Year - dob.Value.Year - (dateEmployed.Value.DayOfYear < dob.Value.DayOfYear ? 1 : 0);
                if (age < 18) Warn(EmployeeImportColumns.DateOfBirth, $"Aged {age} at Date Employed — check the dates.");
                else if (age > 70) Warn(EmployeeImportColumns.DateOfBirth, $"Aged {age} at Date Employed — check the dates.");
            }
        }
        dto.DateOfBirth = dob;

        var endDate = Date(Get(EmployeeImportColumns.ContractEndDate), EmployeeImportColumns.ContractEndDate, "Contract End Date", Err);
        var fixedTerm = employmentType is EmploymentType.Contract or EmploymentType.FixedTerm;
        if (fixedTerm && endDate == null && string.IsNullOrWhiteSpace(Get(EmployeeImportColumns.ContractEndDate)))
            Err(EmployeeImportColumns.ContractEndDate, $"Contract End Date is required for {employmentType} staff.");
        if (endDate != null && dateEmployed != null && endDate <= dateEmployed)
            Err(EmployeeImportColumns.ContractEndDate, "Contract End Date is not after Date Employed.");
        if (endDate != null && employmentType == EmploymentType.Permanent)
        {
            Warn(EmployeeImportColumns.ContractEndDate, "A Contract End Date on a Permanent employee is ignored.");
            endDate = null;
        }

        // Organisation
        var departmentText = Get(EmployeeImportColumns.Department);
        DepartmentRef? department = null;
        if (string.IsNullOrWhiteSpace(departmentText)) Err(EmployeeImportColumns.Department, "Department is required.");
        else if (refs.Departments.TryResolve(departmentText, out var d)) { department = d; dto.DepartmentId = d.Id; }
        else Err(EmployeeImportColumns.Department, $"Department '{departmentText}' is not on the Departments sheet.", refs.Departments.Suggest(departmentText));

        var sectionText = Get(EmployeeImportColumns.Section);
        if (!string.IsNullOrWhiteSpace(sectionText))
        {
            if (refs.Sections.TryResolve(sectionText, out var s))
            {
                if (department != null && s.DepartmentId != department.Id)
                    Err(EmployeeImportColumns.Section, $"Section '{s.Name}' does not belong to department '{department.Name}'.");
                else dto.SectionId = s.Id;
            }
            else if (department != null && EmployeeImportColumns.NormalizeKey(sectionText) == EmployeeImportColumns.NormalizeKey(department.Name))
                Warn(EmployeeImportColumns.Section, "Section repeats the Department name; treated as no section.");
            else
                Err(EmployeeImportColumns.Section, $"Section '{sectionText}' is not on the Sections sheet.", refs.Sections.Suggest(sectionText));
        }

        var positionText = Get(EmployeeImportColumns.Position);
        PositionRef? position = null;
        if (string.IsNullOrWhiteSpace(positionText)) Err(EmployeeImportColumns.Position, "Position is required.");
        else if (refs.Positions.TryResolve(positionText, out var p))
        {
            position = p;
            dto.PositionId = p.Id;
            dto.OrganizationUnitId = p.OrganizationUnitId;
        }
        else Err(EmployeeImportColumns.Position, $"Position '{positionText}' is not on the Positions sheet.", refs.Positions.Suggest(positionText));

        var locationText = Get(EmployeeImportColumns.Location);
        if (string.IsNullOrWhiteSpace(locationText)) Err(EmployeeImportColumns.Location, "Location is required: every employee is placed somewhere.");
        else if (refs.Locations.TryResolve(locationText, out var l)) dto.LocationId = l.Id;
        else Err(EmployeeImportColumns.Location, $"Location '{locationText}' is not on the Locations sheet.", refs.Locations.Suggest(locationText));

        // Payroll membership, salary structure
        var onPayroll = true;
        var onPayrollText = Get(EmployeeImportColumns.OnPayroll);
        if (!string.IsNullOrWhiteSpace(onPayrollText))
        {
            if (EmployeeImportValues.TryParseYesNo(onPayrollText, out var yes)) onPayroll = yes;
            else Err(EmployeeImportColumns.OnPayroll, $"On Payroll must be Yes or No, not '{onPayrollText}'.");
        }
        dto.IsOnPayroll = onPayroll;

        var reasonText = Get(EmployeeImportColumns.OffPayrollReason);
        if (!onPayroll)
        {
            if (string.IsNullOrWhiteSpace(reasonText))
                Err(EmployeeImportColumns.OffPayrollReason, "An employee who is not on payroll needs an Off-Payroll Reason.");
            else if (EmployeeImportValues.TryParseEnum<OffPayrollReason>(reasonText, out var reason)) dto.OffPayrollReason = reason;
            else Err(EmployeeImportColumns.OffPayrollReason, $"Off-Payroll Reason '{reasonText}' is not one of: {string.Join(", ", Enum.GetNames<OffPayrollReason>())}.");
            dto.OffPayrollNote = "Imported from the employee register.";
        }
        else if (!string.IsNullOrWhiteSpace(reasonText))
            Warn(EmployeeImportColumns.OffPayrollReason, "Off-Payroll Reason is ignored because On Payroll is Yes.");

        var salary = Money(Get(EmployeeImportColumns.MonthlyBasicSalary), EmployeeImportColumns.MonthlyBasicSalary, "Monthly Basic Salary", Err);
        if (salary is < 0) Err(EmployeeImportColumns.MonthlyBasicSalary, "Monthly Basic Salary cannot be negative.");
        if (salary is > 0 && !onPayroll) Err(EmployeeImportColumns.MonthlyBasicSalary, "A salary cannot be recorded for somebody who is not on payroll. Leave it blank or set On Payroll to Yes.");
        if (onPayroll) dto.Salary = salary;

        var levelText = Get(EmployeeImportColumns.SalaryLevel);
        var notchNumber = WholeNumber(Get(EmployeeImportColumns.Notch), EmployeeImportColumns.Notch, "Notch", Err);
        if (!string.IsNullOrWhiteSpace(levelText))
        {
            if (!refs.SalaryLevels.TryGetValue(EmployeeImportColumns.NormalizeCode(levelText), out var level))
            {
                var known = refs.SalaryLevels.Values.Select(v => v.Code).OrderBy(c => c).ToList();
                Err(EmployeeImportColumns.SalaryLevel, $"Salary Level '{levelText}' is not on the Salary Structure sheet.",
                    known.Where(k => k.StartsWith(EmployeeImportColumns.NormalizeCode(levelText)[..Math.Min(1, EmployeeImportColumns.NormalizeCode(levelText).Length)], StringComparison.OrdinalIgnoreCase)).Take(3).ToList());
            }
            else if (!onPayroll)
                Err(EmployeeImportColumns.SalaryLevel, "A salary level cannot be assigned to somebody who is not on payroll.");
            else
            {
                resolved.Salary = new EmployeeImportResolvedSalary { GradeId = level.GradeId, LevelId = level.Id, LevelCode = level.Code };
                var notches = refs.NotchesByLevel.GetValueOrDefault(level.Id) ?? new List<SalaryNotchRef>();
                if (notchNumber == null)
                {
                    if (string.IsNullOrWhiteSpace(Get(EmployeeImportColumns.Notch)))
                        Warn(EmployeeImportColumns.Notch, $"No Notch given for level {level.Code}; the level is assigned without a notch.");
                }
                else
                {
                    var notch = notches.FirstOrDefault(n => n.Number == notchNumber.Value);
                    if (notch == null)
                        Err(EmployeeImportColumns.Notch, notches.Count == 0
                            ? $"Level {level.Code} has no notches on record."
                            : $"Notch {notchNumber} does not exist under level {level.Code} (notches {notches.Min(n => n.Number)}–{notches.Max(n => n.Number)}).");
                    else
                    {
                        resolved.Salary.NotchId = notch.Id;
                        resolved.Salary.NotchNumber = notch.Number;
                        if (salary is > 0 && notch.Amount > 0)
                        {
                            var monthly = notch.Amount;
                            var asMonthlyFromAnnual = notch.Amount / 12m;
                            var deviation = Math.Min(Math.Abs(salary.Value - monthly) / monthly, Math.Abs(salary.Value - asMonthlyFromAnnual) / asMonthlyFromAnnual);
                            if (deviation > 0.05m)
                                Warn(EmployeeImportColumns.MonthlyBasicSalary, $"Monthly Basic Salary {salary:N2} differs from the amount on record for {level.Code} notch {notch.Number} ({notch.Amount:N2}) by more than 5%.");
                        }
                    }
                }
            }
        }
        else if (notchNumber != null)
            Warn(EmployeeImportColumns.Notch, "Notch is ignored because no Salary Level is given.");

        // Staff-number register shape (warning only: TDC open question 4 — accept is the default)
        if (employmentType != null && row.StaffNumber != null && refs.Rules.TryGetValue(employmentType.Value, out var rule) && rule is { AutoGenerate: true })
        {
            var yearNow = DateTime.UtcNow.Year;
            var yearEmployed = dateEmployed?.Year ?? yearNow;
            if (!rule.TryReadSequence(row.StaffNumber, yearNow, out _) && !rule.TryReadSequence(row.StaffNumber, yearEmployed, out _))
                Warn(EmployeeImportColumns.StaffNumber, $"Staff Number '{row.StaffNumber}' does not match the {employmentType} register's format (e.g. {rule.Example(yearNow)}). It is accepted as given; the counter will not learn from it.");
        }

        // Contact
        var email = Get(EmployeeImportColumns.Email);
        if (string.IsNullOrWhiteSpace(email)) Warn(EmployeeImportColumns.Email, "No email address.");
        else if (!EmailRegex.IsMatch(email.Trim()) || email.Trim().Length > 200) Err(EmployeeImportColumns.Email, $"'{email}' is not a valid email address.");
        else
        {
            var normalized = email.Trim().ToLowerInvariant();
            if (refs.ExistingEmails.Contains(normalized)) Err(EmployeeImportColumns.Email, $"Email '{normalized}' already belongs to another employee.");
            else dto.EmailAddress = normalized;
        }

        dto.MobileNumber = Phone(Get(EmployeeImportColumns.MobileNumber), EmployeeImportColumns.MobileNumber, "Mobile Number", Warn);
        if (dto.MobileNumber == null && string.IsNullOrWhiteSpace(Get(EmployeeImportColumns.MobileNumber))) Warn(EmployeeImportColumns.MobileNumber, "No mobile number.");
        dto.TelephoneNumber = Phone(Get(EmployeeImportColumns.Telephone), EmployeeImportColumns.Telephone, "Telephone", Warn);

        var ssnit = Text(Get(EmployeeImportColumns.SsnitNumber), 50, EmployeeImportColumns.SsnitNumber, Err);
        if (ssnit != null)
        {
            if (refs.ExistingSsnitNumbers.Contains(EmployeeImportColumns.NormalizeKey(ssnit))) Err(EmployeeImportColumns.SsnitNumber, "SSNIT Number already belongs to another employee.");
            else dto.SocialSecurityNumber = ssnit;
        }
        var tin = Text(Get(EmployeeImportColumns.Tin), 50, EmployeeImportColumns.Tin, Err);
        if (tin != null)
        {
            if (refs.ExistingTinNumbers.Contains(EmployeeImportColumns.NormalizeKey(tin))) Err(EmployeeImportColumns.Tin, "TIN already belongs to another employee.");
            else dto.TINNumber = tin;
        }

        dto.DigitalAddress = Text(Get(EmployeeImportColumns.DigitalAddress), 50, EmployeeImportColumns.DigitalAddress, Err);
        dto.Address = Text(Get(EmployeeImportColumns.ResidentialAddress), 500, EmployeeImportColumns.ResidentialAddress, Err);
        dto.City = Text(Get(EmployeeImportColumns.City), 100, EmployeeImportColumns.City, Err);
        dto.State = Text(Get(EmployeeImportColumns.Region), 50, EmployeeImportColumns.Region, Err);
        dto.Hometown = Text(Get(EmployeeImportColumns.Hometown), 150, EmployeeImportColumns.Hometown, Err);
        dto.Religion = Text(Get(EmployeeImportColumns.Religion), 50, EmployeeImportColumns.Religion, Err);
        dto.Notes = Get(EmployeeImportColumns.Notes)?.Trim();
        dto.IsFullTime = employmentType != EmploymentType.PartTime;
        dto.StaffStatus = StaffStatus.Active;

        // Identification documents — one pair of columns per type the tenant configured
        foreach (var type in refs.IdentificationTypes)
        {
            var numberKey = EmployeeImportColumns.IdNumberKey(type.Id);
            var expiryKey = EmployeeImportColumns.IdExpiryKey(type.Id);
            var number = Text(Get(numberKey), 100, numberKey, Err);
            var expiry = Date(Get(expiryKey), expiryKey, $"{type.Name} Expiry", Err);
            if (number == null)
            {
                if (expiry != null) Warn(expiryKey, $"{type.Name} Expiry is ignored because no {type.Name} Number is given.");
                continue;
            }
            if (refs.ExistingIdNumbersByType.TryGetValue(type.Id, out var existing) && existing.Contains(EmployeeImportColumns.NormalizeKey(number)))
                Err(numberKey, $"{type.Name} Number '{number}' already belongs to another employee.");
            if (expiry != null && !type.HasExpiryDate) { Warn(expiryKey, $"{type.Name} does not expire; the expiry date is ignored."); expiry = null; }
            if (expiry != null && expiry < today) Warn(expiryKey, $"{type.Name} expired on {EmployeeImportValues.FormatDate(expiry.Value)}.");
            resolved.Identifications.Add(new EmployeeImportResolvedIdentification
            {
                IdentificationTypeId = type.Id, TypeName = type.Name, DocumentNumber = number, ExpiryDate = expiry,
            });
        }

        // Qualifications
        var institution = Text(Get(EmployeeImportColumns.Institution), 200, EmployeeImportColumns.Institution, Err);
        var year = WholeNumber(Get(EmployeeImportColumns.YearCompleted), EmployeeImportColumns.YearCompleted, "Year Completed", Err);
        if (year is < 1940 or > 2100) { Err(EmployeeImportColumns.YearCompleted, $"Year Completed {year} is not a plausible year."); year = null; }
        var highest = Qualification(Get(EmployeeImportColumns.HighestQualification));
        if (highest != null)
        {
            var q = new EmployeeImportResolvedQualification { Kind = "Highest", Institution = institution ?? "Not recorded", YearCompleted = year };
            if (refs.Qualifications.TryResolve(highest, out var master)) q.QualificationId = master.Id; else q.CustomName = highest.Length > 200 ? highest[..200] : highest;
            if (institution == null) Warn(EmployeeImportColumns.Institution, "Institution is blank; the qualification is recorded as 'Not recorded' until completed.");
            resolved.Qualifications.Add(q);
        }
        else if (institution != null || year != null)
            Warn(EmployeeImportColumns.HighestQualification, "Institution / Year Completed are ignored because no Highest Qualification is given.");

        var professional = Qualification(Get(EmployeeImportColumns.ProfessionalQualification));
        if (professional != null)
        {
            if (professional.Contains('/'))
                Warn(EmployeeImportColumns.ProfessionalQualification, "Several qualifications appear in one cell; they are recorded as one entry. Split them on the profile if each needs its own record.");
            var q = new EmployeeImportResolvedQualification { Kind = "Professional", Institution = "Not recorded" };
            if (refs.Qualifications.TryResolve(professional, out var master)) q.QualificationId = master.Id; else q.CustomName = professional.Length > 200 ? professional[..200] : professional;
            resolved.Qualifications.Add(q);
        }

        // Children that need the whole row to be sound
        if (endDate != null && dateEmployed != null && row.StaffNumber != null)
            resolved.Contract = new EmployeeImportResolvedContract
            {
                ContractNumber = $"{row.StaffNumber}/{dateEmployed:yyyyMM}",
                StartDate = dateEmployed.Value,
                EndDate = endDate.Value,
                MonthlySalary = onPayroll ? salary ?? 0m : 0m,
            };

        row.Resolved = resolved;
    }

    // ── Cross-row checks ─────────────────────────────────────────────────────────────────────

    private static void CheckInFileDuplicates(List<EmployeeImportParsedRow> rows, Dictionary<string, int> columnIndex, IXLWorksheet sheet)
    {
        void Check(string key, string label, Func<EmployeeImportParsedRow, string?> select)
        {
            var groups = rows
                .Select(r => (Row: r, Value: EmployeeImportColumns.NormalizeKey(select(r))))
                .Where(p => p.Value.Length > 0)
                .GroupBy(p => p.Value)
                .Where(g => g.Count() > 1);
            foreach (var group in groups)
            {
                var numbers = group.Select(g => g.Row.RowNumber).OrderBy(n => n).ToList();
                foreach (var (row, _) in group)
                {
                    var others = numbers.Where(n => n != row.RowNumber).Select(n => n.ToString());
                    var cell = columnIndex.TryGetValue(key, out var c) ? $"{EmployeeImportColumns.EmployeesSheet}!{sheet.Cell(row.RowNumber, c).Address}" : null;
                    row.Findings.Add(Error(key, cell, $"{label} also appears on row {string.Join(", ", others)} of this file."));
                }
            }
        }

        Check(EmployeeImportColumns.StaffNumber, "Staff Number", r => r.Raw.GetValueOrDefault(EmployeeImportColumns.StaffNumber));
        Check(EmployeeImportColumns.Email, "Email", r => r.Resolved?.Employee.EmailAddress);
        Check(EmployeeImportColumns.SsnitNumber, "SSNIT Number", r => r.Resolved?.Employee.SocialSecurityNumber);
        Check(EmployeeImportColumns.Tin, "TIN", r => r.Resolved?.Employee.TINNumber);

        var typeIds = rows.SelectMany(r => r.Resolved?.Identifications ?? new List<EmployeeImportResolvedIdentification>())
            .Select(i => (i.IdentificationTypeId, i.TypeName)).Distinct();
        foreach (var (typeId, typeName) in typeIds)
            Check(EmployeeImportColumns.IdNumberKey(typeId), $"{typeName} Number",
                r => r.Resolved?.Identifications.FirstOrDefault(i => i.IdentificationTypeId == typeId)?.DocumentNumber);
    }

    private static void ResolveManagers(List<EmployeeImportParsedRow> rows, EmployeeImportReferenceData refs, Dictionary<string, int> columnIndex, IXLWorksheet sheet)
    {
        var byNumber = rows.Where(r => r.StaffNumber != null)
            .GroupBy(r => EmployeeImportColumns.NormalizeKey(r.StaffNumber))
            .ToDictionary(g => g.Key, g => g.First());

        foreach (var row in rows)
        {
            var managerText = row.Raw.GetValueOrDefault(EmployeeImportColumns.ManagerStaffNumber);
            if (string.IsNullOrWhiteSpace(managerText) || row.Resolved == null) continue;
            var key = EmployeeImportColumns.NormalizeKey(managerText);
            var cell = columnIndex.TryGetValue(EmployeeImportColumns.ManagerStaffNumber, out var c)
                ? $"{EmployeeImportColumns.EmployeesSheet}!{sheet.Cell(row.RowNumber, c).Address}" : null;

            if (row.StaffNumber != null && key == EmployeeImportColumns.NormalizeKey(row.StaffNumber))
            {
                row.Findings.Add(Error(EmployeeImportColumns.ManagerStaffNumber, cell, "An employee cannot be their own manager."));
                continue;
            }
            if (byNumber.TryGetValue(key, out var managerRow))
            {
                row.ManagerRowNumber = managerRow.RowNumber;
                row.Resolved.ManagerRowNumber = managerRow.RowNumber;
                if (managerRow.ErrorCount > 0)
                    row.Findings.Add(Warning(EmployeeImportColumns.ManagerStaffNumber, cell, $"The manager is row {managerRow.RowNumber} of this file, which has errors; the manager link is set only if that row imports."));
                continue;
            }
            if (refs.ExistingEmployeeNumbers.TryGetValue(key, out var managerId))
            {
                // Guid.Empty marks a soft-deleted employee: their number is still taken, but they cannot manage anyone.
                if (managerId == Guid.Empty)
                    row.Findings.Add(Warning(EmployeeImportColumns.ManagerStaffNumber, cell, $"Manager Staff Number '{managerText}' belongs to a former employee; imported without a manager."));
                else
                    row.Resolved.Employee.ManagerId = managerId;
                continue;
            }
            row.Findings.Add(Warning(EmployeeImportColumns.ManagerStaffNumber, cell, $"Manager Staff Number '{managerText}' is not in this file or in the system; imported without a manager."));
        }
    }

    // ── Cell readers ─────────────────────────────────────────────────────────────────────────

    /// <summary>Reads a cell as the text the checker will interpret, noting when Excel's type disagrees with the column.</summary>
    private static string? ReadCell(IXLCell cell, EmployeeImportColumn column, EmployeeImportParsedRow row)
    {
        if (cell.IsEmpty()) return null;
        switch (cell.DataType)
        {
            case XLDataType.DateTime:
                var date = DateOnly.FromDateTime(cell.GetDateTime());
                return column.Kind == EmployeeImportColumnKind.Date
                    ? EmployeeImportValues.FormatDate(date)
                    : cell.GetFormattedString();
            case XLDataType.Number:
                var number = cell.GetDouble();
                if (column.Kind == EmployeeImportColumnKind.Date)
                {
                    // A date typed into a General cell arrives as a serial; honour it.
                    if (number is > 10_000 and < 100_000) return EmployeeImportValues.FormatDate(DateOnly.FromDateTime(DateTime.FromOADate(number)));
                    return number.ToString(CultureInfo.InvariantCulture);
                }
                if (column.TextFormat)
                    row.Findings.Add(Warning(column.Key, $"{EmployeeImportColumns.EmployeesSheet}!{cell.Address}",
                        $"{column.Header} was typed as a number; a leading zero, if there was one, has been lost."));
                return number == Math.Floor(number) && Math.Abs(number) < 1e15
                    ? ((long)number).ToString(CultureInfo.InvariantCulture)
                    : number.ToString(CultureInfo.InvariantCulture);
            case XLDataType.Boolean:
                return cell.GetBoolean() ? "Yes" : "No";
            case XLDataType.Text:
                var text = cell.GetText().Trim();
                return text.Length == 0 ? null : text;
            default:
                var formatted = cell.GetFormattedString().Trim();
                return formatted.Length == 0 ? null : formatted;
        }
    }

    private static string? ReadText(IXLCell cell)
    {
        if (cell.IsEmpty()) return null;
        var text = cell.DataType == XLDataType.Text ? cell.GetText() : cell.GetFormattedString();
        text = text.Trim();
        return text.Length == 0 ? null : text;
    }

    private static string? Text(string? value, int maxLength, string key, Action<string, string, List<string>?> err)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        var text = value.Trim();
        if (text.Length > maxLength) { err(key, $"Longer than {maxLength} characters.", null); return null; }
        return text;
    }

    private static DateOnly? Date(string? value, string key, string label, Action<string, string, List<string>?> err)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        if (EmployeeImportValues.TryParseDate(value, out var date)) return date;
        err(key, $"{label} '{value}' is not a date. Type a real date such as 08/07/1970.", null);
        return null;
    }

    private static decimal? Money(string? value, string key, string label, Action<string, string, List<string>?> err)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        var text = value.Replace(",", "").Replace("GHS", "", StringComparison.OrdinalIgnoreCase).Trim();
        if (decimal.TryParse(text, NumberStyles.Number, CultureInfo.InvariantCulture, out var d)) return Math.Round(d, 2);
        err(key, $"{label} '{value}' is not a number.", null);
        return null;
    }

    private static int? WholeNumber(string? value, string key, string label, Action<string, string, List<string>?> err)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        var digits = new string(value.Where(char.IsDigit).ToArray());
        if (digits.Length > 0 && digits.Length <= 9 && int.TryParse(digits, out var n) && value.Trim().Length - digits.Length <= 1) return n;
        err(key, $"{label} '{value}' is not a whole number.", null);
        return null;
    }

    private static string? Phone(string? value, string key, string label, Action<string, string, List<string>?> warn)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        var text = value.Trim();
        if (text.Length > 50) { warn(key, $"{label} is longer than 50 characters and was left blank.", null); return null; }
        if (!PhoneRegex.IsMatch(text)) warn(key, $"{label} '{text}' does not look like a phone number.", null);
        return text;
    }

    private static string? Qualification(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return null;
        var text = value.Trim();
        return EmployeeImportColumns.NormalizeKey(text) is "N/A" or "NA" or "NONE" or "NIL" or "-" ? null : text;
    }

    private static EmployeeImportFindingDto Error(string? column, string? cell, string message, List<string>? suggestions = null) => new()
    {
        Severity = EmployeeImportFindingSeverity.Error, Column = column, Cell = cell, Message = message, Suggestions = suggestions ?? new List<string>(),
    };

    private static EmployeeImportFindingDto Warning(string? column, string? cell, string message, List<string>? suggestions = null) => new()
    {
        Severity = EmployeeImportFindingSeverity.Warning, Column = column, Cell = cell, Message = message, Suggestions = suggestions ?? new List<string>(),
    };
}
