<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**\*</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj\**\*.cs;artifacts\**\*.cs" />
    <EmbeddedResource Remove="obj\**\*;artifacts\**\*" />
    <None Remove="obj\**\*;artifacts\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

</Project>
