'use client';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, ArrowRight, CalendarDays, Check, Save } from 'lucide-react';
import { Badge } from '@/components/ui/badge'; import { Button } from '@/components/ui/button'; import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label'; import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select'; import { Switch } from '@/components/ui/switch'; import { Textarea } from '@/components/ui/textarea';
import { saveDemoTemplate } from '@/lib/finance/recurring-journal-demo';
export default function NewRecurringJournalPage(){
 const router=useRouter(); const [step,setStep]=useState(1); const [name,setName]=useState('Monthly Management Fee Accrual'); const [description,setDescription]=useState('Accrue monthly management fees and allocate across operating departments.'); const [frequency,setFrequency]=useState('Monthly'); const [amount,setAmount]=useState('30000'); const [day,setDay]=useState('Last business day'); const [autoReverse,setAutoReverse]=useState(true); const [reference,setReference]=useState('MGMT-{Period}-{Sequence}');
 const dates=useMemo(()=>['31 Jul 2026','31 Aug 2026','30 Sep 2026','30 Oct 2026','30 Nov 2026'],[frequency,day]);
 const submit=()=>{const id='demo-'+Date.now();saveDemoTemplate({id,templateNumber:`RJ-2026-${String(Date.now()).slice(-4)}`,name,description,frequency,schedule:day,nextDue:'2026-07-31',amount:Number(amount),status:'Pending Approval',owner:'Akwasi Adu-Kyeremeh',autoReverse,referencePattern:reference,submittedAt:new Date().toISOString()});router.push(`/finance/recurring-journals/${id}`)};
 return <div className="mx-auto max-w-6xl space-y-6"><div><Badge variant="outline" className="mb-2 border-blue-300 text-blue-700">Demo Preview</Badge><h1 className="text-3xl font-bold">New Recurring Journal</h1><p className="text-muted-foreground">Create a controlled, approval-backed recurring journal template.</p></div><div className="grid grid-cols-4 gap-2">{['Basics','Journal lines','Schedule','Review'].map((x,i)=><div key={x} className={`rounded-lg border p-3 text-sm ${step===i+1?'border-blue-600 bg-blue-50 text-blue-800':step>i+1?'bg-emerald-50 text-emerald-800':''}`}><span className="mr-2 font-bold">{step>i+1?<Check className="inline h-4 w-4"/>:i+1}</span>{x}</div>)}</div>
 {step===1&&<Card><CardHeader><CardTitle>Template basics</CardTitle></CardHeader><CardContent className="grid gap-5 md:grid-cols-2"><div><Label>Name</Label><Input value={name} onChange={e=>setName(e.target.value)}/></div><div><Label>Reference pattern</Label><Input value={reference} onChange={e=>setReference(e.target.value)}/><p className="mt-1 text-xs text-muted-foreground">Tokens: {'{TemplateNumber} {Period} {ScheduledDate} {Sequence}'}</p></div><div className="md:col-span-2"><Label>Description</Label><Textarea value={description} onChange={e=>setDescription(e.target.value)}/></div></CardContent></Card>}
 {step===2&&<Card><CardHeader><CardTitle>Balanced journal & allocation</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><div><Label>Fixed template total (GHS)</Label><Input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></div><div><Label>Book</Label><Input value="IFRS" readOnly/></div><div><Label>Allocation method</Label><Input value="Percentage allocation" readOnly/></div></div><div className="overflow-hidden rounded-lg border"><table className="w-full text-sm"><thead className="bg-muted"><tr><th className="p-3 text-left">Account / dimension</th><th>Debit</th><th>Credit</th><th>Allocation</th></tr></thead><tbody><tr className="border-t"><td className="p-3">610100 · Management Fees<br/><span className="text-xs text-muted-foreground">Departments: Operations 60% · Administration 40%</span></td><td className="text-center">GHS {Number(amount).toLocaleString()}</td><td></td><td className="text-center">100%</td></tr><tr className="border-t"><td className="p-3">220200 · Accrued Expenses</td><td></td><td className="text-center">GHS {Number(amount).toLocaleString()}</td><td></td></tr></tbody></table></div><div className="rounded-md bg-emerald-50 p-3 text-sm text-emerald-800">Balanced · Debits and credits both equal GHS {Number(amount).toLocaleString()}</div></CardContent></Card>}
 {step===3&&<Card><CardHeader><CardTitle>Schedule & reversal</CardTitle></CardHeader><CardContent className="grid gap-5 md:grid-cols-2"><div><Label>Frequency</Label><Select value={frequency} onValueChange={setFrequency}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['Weekly','Semi-monthly','Monthly','Quarterly','Annually','Custom rule'].map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Run rule</Label><Select value={day} onValueChange={setDay}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['Last business day','1st and 15th','15th and month-end','First Monday','Selected weekdays'].map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select></div><div><Label>Starts</Label><Input type="date" defaultValue="2026-07-31"/></div><div><Label>End condition</Label><Select defaultValue="none"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">No end date</SelectItem><SelectItem value="date">Specific date</SelectItem><SelectItem value="count">Maximum occurrences</SelectItem></SelectContent></Select></div><div className="flex items-center justify-between rounded-lg border p-4 md:col-span-2"><div><p className="font-medium">Automatic reversal</p><p className="text-sm text-muted-foreground">Create reversal draft on first day of next fiscal period; approval still required.</p></div><Switch checked={autoReverse} onCheckedChange={setAutoReverse}/></div><div className="rounded-lg border bg-blue-50/60 p-4 md:col-span-2"><p className="mb-3 flex items-center gap-2 font-medium"><CalendarDays className="h-4 w-4"/>Next five scheduled dates</p><div className="flex flex-wrap gap-2">{dates.map(x=><Badge key={x} variant="outline" className="bg-white">{x}</Badge>)}</div><p className="mt-3 text-xs text-muted-foreground">Business-day policy: Next business day; previous business day when month-end would cross a fiscal period.</p></div></CardContent></Card>}
 {step===4&&<Card><CardHeader><CardTitle>Review and submit for activation</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-4 md:grid-cols-3">{[['Template',name],['Amount',`GHS ${Number(amount).toLocaleString()}`],['Schedule',`${frequency} · ${day}`],['Reference',reference],['Reversal',autoReverse?'First day next period':'None'],['Workflow','Accounts Officer → Finance Manager → Financial Controller']].map(([a,b])=><div className="rounded-lg border p-4" key={a}><p className="text-xs text-muted-foreground">{a}</p><p className="mt-1 font-medium">{b}</p></div>)}</div><div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Demo action: submission stores this template only in this browser and displays the planned Pending Approval state. No workflow or GL posting occurs.</div></CardContent></Card>}
 <div className="flex justify-between"><Button variant="outline" onClick={()=>step===1?router.push('/finance/recurring-journals'):setStep(step-1)}><ArrowLeft className="mr-2 h-4 w-4"/>{step===1?'Cancel':'Back'}</Button>{step<4?<Button onClick={()=>setStep(step+1)}>Continue<ArrowRight className="ml-2 h-4 w-4"/></Button>:<Button onClick={submit}><Save className="mr-2 h-4 w-4"/>Submit for activation</Button>}</div></div>
}
