'use client';

import { useParams, useSearchParams } from 'next/navigation';
import { InterviewScorecardForm } from '@/components/hr/recruitment/InterviewScorecardForm';

/**
 * A panelist's own scorecard, in their own portal (round 4, lane F5).
 *
 * <b>Why this route exists.</b> Until now the only way for a panelist to file a scorecard was to go
 * to HR's interview desk at `/hr/recruitment/interviews/{id}`, find the Candidates tab, and press a
 * button on a row — three clicks and a tab, through a screen built for the person who *scheduled*
 * the interview rather than the person sitting on it. The portal diary meanwhile described itself as
 * "the scorecards you owe" and listed interview numbers.
 *
 * ⚠ **It renders the same `InterviewScorecardForm` as HR's route.** The earlier decision against a
 * portal scorecard was that it would mean *"two scorecard forms against one upsert endpoint, which
 * is how a scorecard gets silently replaced"* — and that objection is about two implementations, not
 * two routes. The form was extracted before this route was added. Do not fork it.
 *
 * No `?panelistId=` is passed: a panelist files as themselves, and the form resolves their seat from
 * the token's employee id. The server would refuse anything else anyway.
 */
export default function MyScorecardPage() {
  const params = useParams();
  const searchParams = useSearchParams();

  const interviewId = params.interviewId as string;
  const intervieweeId = params.intervieweeId as string;

  return (
    <InterviewScorecardForm
      interviewId={interviewId}
      intervieweeId={intervieweeId}
      // Honoured if present, so an emailed or bookmarked link still lands on the right seat — but
      // never generated by this side of the app.
      panelistIdFromQuery={searchParams.get('panelistId')}
      backHref="/me/panel"
    />
  );
}
