import type { Account, AccountSegmentValue } from '@/types/finance';

/**
 * Mock data for Segmented Chart of Accounts
 * Account Number Format: DEPT-CC-NAT (e.g., 100-200-1000)
 * - Segment 1: Department (3 digits)
 * - Segment 2: Cost Center (3 digits)
 * - Segment 3: Natural Account (4 digits)
 */
export const SEGMENTED_COA_ACCOUNTS: Account[] = [
    // ===== ASSETS - Finance Department, Head Office =====
    {
        id: 'seg-acc-1',
        tenantId: 'tenant-1',
        accountCode: '100-200-1000',
        accountNumber: '100-200-1000',
        accountName: 'Cash - Finance Dept - Head Office',
        accountType: 'Asset',
        accountCategory: 'Current Assets',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-1', accountId: 'seg-acc-1', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '100', segmentDescription: 'Finance Department' },
            { id: 'sv-2', accountId: 'seg-acc-1', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-3', accountId: 'seg-acc-1', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '1000', segmentDescription: 'Cash' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 150000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'seg-acc-2',
        tenantId: 'tenant-1',
        accountCode: '100-200-1100',
        accountNumber: '100-200-1100',
        accountName: 'Accounts Receivable - Finance Dept - Head Office',
        accountType: 'Asset',
        accountCategory: 'Current Assets',
        currencyCode: 'GHS',
        isMultiCurrency: true,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-4', accountId: 'seg-acc-2', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '100', segmentDescription: 'Finance Department' },
            { id: 'sv-5', accountId: 'seg-acc-2', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-6', accountId: 'seg-acc-2', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '1100', segmentDescription: 'Accounts Receivable' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: true,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 95000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== ASSETS - Sales Department, Branch 1 =====
    {
        id: 'seg-acc-3',
        tenantId: 'tenant-1',
        accountCode: '200-300-1000',
        accountNumber: '200-300-1000',
        accountName: 'Cash - Sales Dept - Branch 1',
        accountType: 'Asset',
        accountCategory: 'Current Assets',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-7', accountId: 'seg-acc-3', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '200', segmentDescription: 'Sales Department' },
            { id: 'sv-8', accountId: 'seg-acc-3', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '300', segmentDescription: 'Branch 1' },
            { id: 'sv-9', accountId: 'seg-acc-3', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '1000', segmentDescription: 'Cash' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 75000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'seg-acc-4',
        tenantId: 'tenant-1',
        accountCode: '200-300-1200',
        accountNumber: '200-300-1200',
        accountName: 'Inventory - Sales Dept - Branch 1',
        accountType: 'Asset',
        accountCategory: 'Current Assets',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-10', accountId: 'seg-acc-4', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '200', segmentDescription: 'Sales Department' },
            { id: 'sv-11', accountId: 'seg-acc-4', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '300', segmentDescription: 'Branch 1' },
            { id: 'sv-12', accountId: 'seg-acc-4', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '1200', segmentDescription: 'Inventory' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 180000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== ASSETS - IT Department, Head Office =====
    {
        id: 'seg-acc-5',
        tenantId: 'tenant-1',
        accountCode: '300-200-1500',
        accountNumber: '300-200-1500',
        accountName: 'Equipment - IT Dept - Head Office',
        accountType: 'Asset',
        accountCategory: 'Fixed Assets',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-13', accountId: 'seg-acc-5', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '300', segmentDescription: 'IT Department' },
            { id: 'sv-14', accountId: 'seg-acc-5', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-15', accountId: 'seg-acc-5', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '1500', segmentDescription: 'Equipment' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 250000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== LIABILITIES - Finance Department, Head Office =====
    {
        id: 'seg-acc-6',
        tenantId: 'tenant-1',
        accountCode: '100-200-2000',
        accountNumber: '100-200-2000',
        accountName: 'Accounts Payable - Finance Dept - Head Office',
        accountType: 'Liability',
        accountCategory: 'Current Liabilities',
        currencyCode: 'GHS',
        isMultiCurrency: true,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-16', accountId: 'seg-acc-6', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '100', segmentDescription: 'Finance Department' },
            { id: 'sv-17', accountId: 'seg-acc-6', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-18', accountId: 'seg-acc-6', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '2000', segmentDescription: 'Accounts Payable' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: true,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -85000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== EQUITY - Corporate =====
    {
        id: 'seg-acc-7',
        tenantId: 'tenant-1',
        accountCode: '100-200-3000',
        accountNumber: '100-200-3000',
        accountName: 'Share Capital - Finance Dept - Head Office',
        accountType: 'Equity',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-19', accountId: 'seg-acc-7', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '100', segmentDescription: 'Finance Department' },
            { id: 'sv-20', accountId: 'seg-acc-7', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-21', accountId: 'seg-acc-7', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '3000', segmentDescription: 'Share Capital' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -500000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== REVENUE - Sales Department, Branch 1 =====
    {
        id: 'seg-acc-8',
        tenantId: 'tenant-1',
        accountCode: '200-300-4000',
        accountNumber: '200-300-4000',
        accountName: 'Sales Revenue - Sales Dept - Branch 1',
        accountType: 'Revenue',
        currencyCode: 'GHS',
        isMultiCurrency: true,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-22', accountId: 'seg-acc-8', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '200', segmentDescription: 'Sales Department' },
            { id: 'sv-23', accountId: 'seg-acc-8', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '300', segmentDescription: 'Branch 1' },
            { id: 'sv-24', accountId: 'seg-acc-8', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '4000', segmentDescription: 'Sales Revenue' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: -450000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'seg-acc-9',
        tenantId: 'tenant-1',
        accountCode: '200-400-4000',
        accountNumber: '200-400-4000',
        accountName: 'Sales Revenue - Sales Dept - Branch 2',
        accountType: 'Revenue',
        currencyCode: 'GHS',
        isMultiCurrency: true,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-25', accountId: 'seg-acc-9', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '200', segmentDescription: 'Sales Department' },
            { id: 'sv-26', accountId: 'seg-acc-9', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '400', segmentDescription: 'Branch 2' },
            { id: 'sv-27', accountId: 'seg-acc-9', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '4000', segmentDescription: 'Sales Revenue' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: -380000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== EXPENSES - Finance Department, Head Office =====
    {
        id: 'seg-acc-10',
        tenantId: 'tenant-1',
        accountCode: '100-200-6000',
        accountNumber: '100-200-6000',
        accountName: 'Salaries - Finance Dept - Head Office',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-28', accountId: 'seg-acc-10', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '100', segmentDescription: 'Finance Department' },
            { id: 'sv-29', accountId: 'seg-acc-10', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-30', accountId: 'seg-acc-10', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '6000', segmentDescription: 'Salaries' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 120000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'seg-acc-11',
        tenantId: 'tenant-1',
        accountCode: '200-300-6000',
        accountNumber: '200-300-6000',
        accountName: 'Salaries - Sales Dept - Branch 1',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-31', accountId: 'seg-acc-11', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '200', segmentDescription: 'Sales Department' },
            { id: 'sv-32', accountId: 'seg-acc-11', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '300', segmentDescription: 'Branch 1' },
            { id: 'sv-33', accountId: 'seg-acc-11', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '6000', segmentDescription: 'Salaries' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 95000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'seg-acc-12',
        tenantId: 'tenant-1',
        accountCode: '300-200-6000',
        accountNumber: '300-200-6000',
        accountName: 'Salaries - IT Dept - Head Office',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-34', accountId: 'seg-acc-12', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '300', segmentDescription: 'IT Department' },
            { id: 'sv-35', accountId: 'seg-acc-12', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-36', accountId: 'seg-acc-12', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '6000', segmentDescription: 'Salaries' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 85000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'seg-acc-13',
        tenantId: 'tenant-1',
        accountCode: '100-200-6100',
        accountNumber: '100-200-6100',
        accountName: 'Rent - Finance Dept - Head Office',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-37', accountId: 'seg-acc-13', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '100', segmentDescription: 'Finance Department' },
            { id: 'sv-38', accountId: 'seg-acc-13', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-39', accountId: 'seg-acc-13', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '6100', segmentDescription: 'Rent' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 30000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== SPECIAL ACCOUNTS (Corporate Level) =====
    {
        id: 'seg-acc-retained',
        tenantId: 'tenant-1',
        accountCode: '100-200-3100',
        accountNumber: '100-200-3100',
        accountName: 'Retained Earnings - Corporate',
        accountType: 'Equity',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-re-1', accountId: 'seg-acc-retained', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '100', segmentDescription: 'Finance Department' },
            { id: 'sv-re-2', accountId: 'seg-acc-retained', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-re-3', accountId: 'seg-acc-retained', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '3100', segmentDescription: 'Retained Earnings' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: false,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -435000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'seg-acc-unrealized',
        tenantId: 'tenant-1',
        accountCode: '100-200-7100',
        accountNumber: '100-200-7100',
        accountName: 'Unrealized Exchange Gain/Loss - Corporate',
        accountType: 'Revenue',
        accountCategory: 'Other Income',
        description: 'Unrealized foreign exchange gains and losses from multi-currency revaluation',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-ue-1', accountId: 'seg-acc-unrealized', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '100', segmentDescription: 'Finance Department' },
            { id: 'sv-ue-2', accountId: 'seg-acc-unrealized', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-ue-3', accountId: 'seg-acc-unrealized', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '7100', segmentDescription: 'Unrealized FX Gain/Loss' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: false,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -12500,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'seg-acc-realized',
        tenantId: 'tenant-1',
        accountCode: '100-200-7200',
        accountNumber: '100-200-7200',
        accountName: 'Realized Exchange Gain/Loss - Corporate',
        accountType: 'Revenue',
        accountCategory: 'Other Income',
        description: 'Realized foreign exchange gains and losses from settled transactions',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-re2-1', accountId: 'seg-acc-realized', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '100', segmentDescription: 'Finance Department' },
            { id: 'sv-re2-2', accountId: 'seg-acc-realized', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-re2-3', accountId: 'seg-acc-realized', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '7200', segmentDescription: 'Realized FX Gain/Loss' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: false,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -8200,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'seg-acc-suspense',
        tenantId: 'tenant-1',
        accountCode: '100-200-9999',
        accountNumber: '100-200-9999',
        accountName: 'Suspense Account - Corporate',
        accountType: 'Asset',
        accountCategory: 'Current Assets',
        description: 'Temporary holding account for unallocated transactions',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: true,
        segmentValues: [
            { id: 'sv-su-1', accountId: 'seg-acc-suspense', segmentStructureId: 'seg-1', segmentPosition: 1, segmentValue: '100', segmentDescription: 'Finance Department' },
            { id: 'sv-su-2', accountId: 'seg-acc-suspense', segmentStructureId: 'seg-2', segmentPosition: 2, segmentValue: '200', segmentDescription: 'Head Office' },
            { id: 'sv-su-3', accountId: 'seg-acc-suspense', segmentStructureId: 'seg-3', segmentPosition: 3, segmentValue: '9999', segmentDescription: 'Suspense' },
        ],
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 0,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
];
