import type { Account } from '@/types/finance';

/**
 * Mock data for Standard (hierarchical) Chart of Accounts
 * Includes Assets, Liabilities, Equity, Revenue, and Expense accounts
 */
export const STANDARD_COA_ACCOUNTS: Account[] = [
    // ===== ASSETS =====
    {
        id: 'acc-1000',
        tenantId: 'tenant-1',
        accountCode: '1000',
        accountNumber: '1000',
        accountName: 'Cash and Cash Equivalents',
        accountType: 'Asset',
        accountCategory: 'Current Assets',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 250000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-1100',
        tenantId: 'tenant-1',
        accountCode: '1100',
        accountNumber: '1100',
        accountName: 'Accounts Receivable',
        accountType: 'Asset',
        accountCategory: 'Current Assets',
        currencyCode: 'GHS',
        isMultiCurrency: true,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: true,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 185000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-1200',
        tenantId: 'tenant-1',
        accountCode: '1200',
        accountNumber: '1200',
        accountName: 'Inventory',
        accountType: 'Asset',
        accountCategory: 'Current Assets',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 320000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-1500',
        tenantId: 'tenant-1',
        accountCode: '1500',
        accountNumber: '1500',
        accountName: 'Property, Plant & Equipment',
        accountType: 'Asset',
        accountCategory: 'Fixed Assets',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: false,
        isControlAccount: true,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 1500000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-1510',
        tenantId: 'tenant-1',
        accountCode: '1510',
        accountNumber: '1510',
        accountName: 'Buildings',
        accountType: 'Asset',
        accountCategory: 'Fixed Assets',
        parentAccountId: 'acc-1500',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 800000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-1520',
        tenantId: 'tenant-1',
        accountCode: '1520',
        accountNumber: '1520',
        accountName: 'Equipment',
        accountType: 'Asset',
        accountCategory: 'Fixed Assets',
        parentAccountId: 'acc-1500',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 450000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-1530',
        tenantId: 'tenant-1',
        accountCode: '1530',
        accountNumber: '1530',
        accountName: 'Vehicles',
        accountType: 'Asset',
        accountCategory: 'Fixed Assets',
        parentAccountId: 'acc-1500',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 250000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== LIABILITIES =====
    {
        id: 'acc-2000',
        tenantId: 'tenant-1',
        accountCode: '2000',
        accountNumber: '2000',
        accountName: 'Accounts Payable',
        accountType: 'Liability',
        accountCategory: 'Current Liabilities',
        currencyCode: 'GHS',
        isMultiCurrency: true,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: true,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -125000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-2100',
        tenantId: 'tenant-1',
        accountCode: '2100',
        accountNumber: '2100',
        accountName: 'Accrued Expenses',
        accountType: 'Liability',
        accountCategory: 'Current Liabilities',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -45000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-2500',
        tenantId: 'tenant-1',
        accountCode: '2500',
        accountNumber: '2500',
        accountName: 'Long-term Debt',
        accountType: 'Liability',
        accountCategory: 'Non-Current Liabilities',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -500000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== EQUITY =====
    {
        id: 'acc-3000',
        tenantId: 'tenant-1',
        accountCode: '3000',
        accountNumber: '3000',
        accountName: 'Share Capital',
        accountType: 'Equity',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -1000000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-3100',
        tenantId: 'tenant-1',
        accountCode: '3100',
        accountNumber: '3100',
        accountName: 'Retained Earnings',
        accountType: 'Equity',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: false,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -435000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== REVENUE =====
    {
        id: 'acc-4000',
        tenantId: 'tenant-1',
        accountCode: '4000',
        accountNumber: '4000',
        accountName: 'Sales Revenue',
        accountType: 'Revenue',
        currencyCode: 'GHS',
        isMultiCurrency: true,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: -850000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-4100',
        tenantId: 'tenant-1',
        accountCode: '4100',
        accountNumber: '4100',
        accountName: 'Service Revenue',
        accountType: 'Revenue',
        currencyCode: 'GHS',
        isMultiCurrency: true,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: -320000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-4900',
        tenantId: 'tenant-1',
        accountCode: '4900',
        accountNumber: '4900',
        accountName: 'Other Income',
        accountType: 'Revenue',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: -25000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },

    // ===== EXPENSES =====
    {
        id: 'acc-5000',
        tenantId: 'tenant-1',
        accountCode: '5000',
        accountNumber: '5000',
        accountName: 'Cost of Goods Sold',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 420000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-6000',
        tenantId: 'tenant-1',
        accountCode: '6000',
        accountNumber: '6000',
        accountName: 'Salaries and Wages',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 280000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-6100',
        tenantId: 'tenant-1',
        accountCode: '6100',
        accountNumber: '6100',
        accountName: 'Rent Expense',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 60000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-6200',
        tenantId: 'tenant-1',
        accountCode: '6200',
        accountNumber: '6200',
        accountName: 'Utilities Expense',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 18000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-6300',
        tenantId: 'tenant-1',
        accountCode: '6300',
        accountNumber: '6300',
        accountName: 'Depreciation Expense',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: false,
        status: 'Active',
        currentBalance: 75000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-6400',
        tenantId: 'tenant-1',
        accountCode: '6400',
        accountNumber: '6400',
        accountName: 'Marketing and Advertising',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 45000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'acc-6500',
        tenantId: 'tenant-1',
        accountCode: '6500',
        accountNumber: '6500',
        accountName: 'Professional Fees',
        accountType: 'Expense',
        currencyCode: 'GHS',
        isMultiCurrency: false,
        isSegmented: false,
        isIFRSClassified: true,
        isBaseClassified: true,
        isLocalClassified: true,
        allowDirectPosting: true,
        isControlAccount: false,
        budgetTrackingEnabled: true,
        status: 'Active',
        currentBalance: 32000,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
];
