<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/ErpSystem.Api/ErpSystem.Api.csproj" />
    <ProjectReference Include="../../../src/ErpSystem.Data/ErpSystem.Data.csproj" />
    <ProjectReference Include="../../../src/ErpSystem.Core/ErpSystem.Core.csproj" />
    <ProjectReference Include="../../../src/ErpSystem.Shared/ErpSystem.Shared.csproj" />
  </ItemGroup>
</Project>
