import type { GlobalSearchRecordSource } from './global-search';

/** Reviewed server-side searches. Paging is applied by each existing authorized API.
 * References and names only: no payroll, balances, contact details or private notes. */
export const GLOBAL_SEARCH_RECORD_SOURCES: GlobalSearchRecordSource[] = [
  { id: 'finance-journals', module: 'Finance', label: 'Journal entry', route: '/finance/journal-entries',
    endpoint: '/finance/journal-entries/search', searchParam: 'search', params: { take: 5 }, itemsPath: '',
    permissions: ['Finance.Read'], idField: 'id', titleFields: ['number', 'title'], statusField: 'status',
    detailPath: '/finance/journal-entries/:id', maxResults: 5 },
  { id: 'finance-fixed-assets', module: 'Finance', label: 'Fixed asset', route: '/finance/fixed-assets/register',
    endpoint: '/finance/fixed-assets/search', searchParam: 'search', params: { take: 5 }, itemsPath: '',
    idField: 'id', titleFields: ['number', 'title'], statusField: 'status',
    detailPath: '/finance/fixed-assets/register/:id', maxResults: 5 },
  // DocumentManagementController applies record visibility before its final result limit.
  { id: 'documents', module: 'Documents', label: 'Document', route: '/document-management/records',
    endpoint: '/document-management/records', searchParam: 'search', params: { take: 5 }, itemsPath: 'data',
    idField: 'id', titleFields: ['documentReference', 'title'], statusField: 'repositoryStatus',
    detailPath: '/document-management/records/:id', maxResults: 5 },
  { id: 'crm-accounts', module: 'CRM', label: 'CRM account', route: '/crm/accounts',
    endpoint: '/crm/accounts', searchParam: 'search', params: { page: 1, pageSize: 5 },
    idField: 'businessPartnerId', titleFields: ['partnerCode', 'partnerName'],
    detailPath: '/crm/accounts/:id', maxResults: 5 },
  { id: 'crm-leads', module: 'CRM', label: 'Lead', route: '/crm/leads',
    endpoint: '/crm/leads', searchParam: 'search', params: { page: 1, pageSize: 5 },
    idField: 'leadId', titleFields: ['fullName', 'companyName'], statusField: 'leadStatus',
    detailPath: '/crm/leads?leadId=:id', maxResults: 5 },
  { id: 'crm-opportunities', module: 'CRM', label: 'Opportunity', route: '/crm/opportunities',
    endpoint: '/crm/opportunities', searchParam: 'search', params: { page: 1, pageSize: 5 },
    idField: 'opportunityId', titleFields: ['name'], statusField: 'stage',
    detailPath: '/crm/opportunities?opportunityId=:id', maxResults: 5 },
  { id: 'crm-quotes', module: 'CRM', label: 'Quotation', route: '/crm/quotes',
    endpoint: '/crm/quotes', searchParam: 'search', params: { page: 1, pageSize: 5 },
    idField: 'quoteId', titleFields: ['documentNumber', 'quoteName'], statusField: 'quoteStatus',
    detailPath: '/crm/quotes?quoteId=:id', maxResults: 5 },
  // Fleet's existing vehicle cards also open the Maintenance Assets inspector.
  { id: 'fleet-vehicles', module: 'Fleet', label: 'Fleet vehicle', route: '/maintenance/fleet/vehicles',
    endpoint: '/maintenance/fleet/vehicles', searchParam: 'searchTerm', params: { page: 1, pageSize: 5 },
    idField: 'id', titleFields: ['assetNumber', 'name'], statusField: 'status',
    detailPath: '/maintenance/assets?recordId=:id', maxResults: 5 },
  { id: 'fleet-trips', module: 'Fleet', label: 'Fleet trip', route: '/maintenance/fleet/trips',
    endpoint: '/maintenance/fleet/trips', searchParam: 'searchTerm', params: { page: 1, pageSize: 5 },
    idField: 'id', titleFields: ['vehicleAssetNumber', 'vehicleName'], statusField: 'status',
    detailPath: '/maintenance/fleet/trips?id=:id', maxResults: 5 },
  { id: 'finance-accounts', module: 'Finance', label: 'GL account', route: '/finance/accounts',
    endpoint: '/finance/accounts', searchParam: 'search', params: { take: 5 }, itemsPath: '',
    idField: 'id', titleFields: ['accountCode', 'accountName'],
    detailPath: '/finance/accounts/:id', maxResults: 5 },
  { id: 'sales-orders', module: 'Sales', label: 'Sales order', route: '/sales/orders',
    endpoint: '/sales/orders', searchParam: 'search', params: { page: 1, pageSize: 5 },
    idField: 'id', titleFields: ['documentNumber'], statusField: 'orderStatus',
    detailPath: '/sales/orders/:id', maxResults: 5 },
  { id: 'sales-deliveries', module: 'Sales', label: 'Delivery note', route: '/sales/deliveries',
    endpoint: '/sales/deliveries', searchParam: 'search', params: { page: 1, pageSize: 5 },
    idField: 'id', titleFields: ['documentNumber'], statusField: 'deliveryStatus',
    detailPath: '/sales/deliveries/:id', maxResults: 5 },
  { id: 'sales-agreements', module: 'Sales', label: 'Sales agreement', route: '/sales/agreements',
    endpoint: '/sales/agreements', searchParam: 'search', params: { page: 1, pageSize: 5 },
    idField: 'id', titleFields: ['documentNumber', 'agreementTitle'], statusField: 'agreementStatus',
    detailPath: '/sales/agreements/:id', maxResults: 5 },
  // Lookup and ticket register share InternalOnly, the same role allowlist and tenant/deleted scope.
  { id: 'helpdesk-tickets', module: 'Helpdesk', label: 'Ticket', route: '/helpdesk/tickets',
    endpoint: '/ehc/internal/lookups/tickets', searchParam: 'q', params: { limit: 5 }, itemsPath: 'data',
    idField: 'id', titleFields: ['ticketNumber', 'subject'], statusField: 'status',
    detailPath: '/helpdesk/tickets/:id', maxResults: 5 },
  // ProjectsController.GetProjectLookup uses the same project-read authorization as its register.
  { id: 'projects', module: 'Projects', label: 'Project', route: '/development/projects',
    endpoint: '/projects/lookup', searchParam: 'search', params: { take: 5 }, itemsPath: '',
    idField: 'id', titleFields: ['projectCode', 'title'], statusField: 'status',
    detailPath: '/development/projects/:id', maxResults: 5 },
  // EmployeesController.GetPaged enforces the established employee read policy.
  { id: 'hr-employees', module: 'Human Resources', label: 'Employee', route: '/hr/employees',
    permissions: ['HR.Employee.Read', 'HR.Employee.Write', 'HR.Employee.Admin'],
    endpoint: '/hr/Employees/paged', method: 'POST', searchIn: 'body', searchParam: 'searchTerm',
    params: { page: 1, pageSize: 5 }, idField: 'id', titleFields: ['employeeNumber', 'fullName'],
    detailPath: '/hr/employees/:id', maxResults: 5 },
  { id: 'hr-leave-requests', module: 'Human Resources', label: 'Leave request', route: '/hr/leave/register',
    permissions: ['HR.Leave.Read', 'HR.Leave.Write', 'HR.Leave.Admin'],
    endpoint: '/Leaves/register', searchParam: 'search', params: { pageNumber: 1, pageSize: 5 },
    idField: 'id', titleFields: ['requestNumber'], statusField: 'status',
    detailPath: '/hr/leave/requests/:id', maxResults: 5 },
  { id: 'estate-land', module: 'Estate', label: 'Land asset', route: '/estate/land-management',
    endpoint: '/estate/managed-assets', searchParam: 'search', params: { assetType: 0, skip: 0, take: 5 },
    itemsPath: 'data', idField: 'id', titleFields: ['assetCode', 'name'], statusField: 'status',
    detailPath: '/estate/land-management?recordId=:id', maxResults: 5 },
  { id: 'finance-ap-invoices', module: 'Finance', label: 'AP invoice', route: '/finance/ap/invoices',
    endpoint: '/ap/invoices', searchParam: 'searchTerm', params: { page: 1, pageSize: 5 },
    idField: 'id', titleFields: ['invoiceNumber'], subtitleFields: ['supplierInvoiceNumber'],
    statusField: 'status', detailPath: '/finance/ap/invoices/:id', maxResults: 5 },
  { id: 'finance-ap-payments', module: 'Finance', label: 'Supplier payment', route: '/finance/ap/payments',
    endpoint: '/ap/payments', searchParam: 'searchTerm', params: { page: 1, pageSize: 5 },
    idField: 'id', titleFields: ['paymentNumber'], statusField: 'status',
    detailPath: '/finance/ap/payments/:id', maxResults: 5 },
  { id: 'finance-ar-invoices', module: 'Finance', label: 'AR invoice', route: '/finance/ar/invoices',
    endpoint: '/ar/invoices', searchParam: 'searchTerm', params: { pageNumber: 1, pageSize: 5 },
    idField: 'id', titleFields: ['invoiceNumber'], statusField: 'status',
    detailPath: '/finance/ar/invoices/:id', maxResults: 5 },
  { id: 'finance-ar-payments', module: 'Finance', label: 'Customer payment', route: '/finance/ar/payments',
    endpoint: '/ar/payments', searchParam: 'searchTerm', params: { pageNumber: 1, pageSize: 5 },
    idField: 'id', titleFields: ['paymentNumber'], statusField: 'status',
    detailPath: '/finance/ar/payments/:id', maxResults: 5 },
  { id: 'maintenance-assets', module: 'Maintenance', label: 'Maintenance asset', route: '/maintenance/assets',
    endpoint: '/maintenance/assets', searchParam: 'searchTerm', params: { page: 1, pageSize: 5 },
    idField: 'id', titleFields: ['assetNumber', 'name'], statusField: 'status',
    detailPath: '/maintenance/assets?recordId=:id', maxResults: 5 },
  { id: 'maintenance-work-orders', module: 'Maintenance', label: 'Work order', route: '/maintenance/work-orders',
    endpoint: '/maintenance/work-orders', searchParam: 'searchTerm', params: { page: 1, pageSize: 5 },
    idField: 'id', titleFields: ['workOrderNumber', 'title'], subtitleFields: ['assetNumber'],
    statusField: 'status', detailPath: '/maintenance/work-orders?recordId=:id', maxResults: 5 },
  { id: 'maintenance-job-cards', module: 'Maintenance', label: 'Job card', route: '/maintenance/job-cards',
    endpoint: '/maintenance/job-cards', searchParam: 'searchTerm', params: { page: 1, pageSize: 5 },
    idField: 'id', titleFields: ['jobCardNumber', 'title'], subtitleFields: ['assetCode'],
    statusField: 'jobCardStatus', detailPath: '/maintenance/job-cards?recordId=:id', maxResults: 5 },
];

/** These registers remain reachable through navigation search. They are deliberately
 * not represented as record searches until their APIs support scoped, bounded text search. */
export const GLOBAL_SEARCH_RECORD_GAPS = [
  { module: 'Quantity Survey', records: 'Historical rate lines', reason: 'Search remains scoped to a selected rate library record.' },
  { module: 'Quantity Survey', records: 'Specialist commercial registers', reason: 'Dayworks, claims, subcontracts, final accounts and other specialist registers need additional scoped owner adapters.' },
  { module: 'Civil Engineering', records: 'Specialist project controls', reason: 'Design, RFI, site instruction, inspection and other control records currently require project-scoped owners.' },
] as const;
