import type { GlobalSearchRecordSource } from './global-search';

// These are the same paged, authenticated searches used by the document registers.
export const GLOBAL_SEARCH_PROCUREMENT_SOURCES: GlobalSearchRecordSource[] = [
  { id: 'procurement-plans', module: 'Procurement', label: 'Procurement plan',
    route: '/procurement/planning/plans', endpoint: '/procurement/procurementplans', searchParam: 'search',
    params: { page: 1, pageSize: 5 }, idField: 'id', titleFields: ['planNumber', 'title'],
    subtitleFields: ['organizationUnitName'], statusField: 'status', detailPath: '/procurement/planning/plans/:id' },
  { id: 'procurement-budgets', module: 'Procurement', label: 'Procurement budget',
    route: '/procurement/planning/budgets', endpoint: '/procurement/procurementbudgets', searchParam: 'search',
    params: { page: 1, pageSize: 5 }, idField: 'id', titleFields: ['budgetCode', 'title'],
    subtitleFields: ['organizationUnitName'], statusField: 'status', detailPath: '/procurement/planning/budgets/:id' },
  { id: 'procurement-contracts', module: 'Procurement', label: 'Procurement contract',
    route: '/procurement/contracts', endpoint: '/procurement/Contracts', searchParam: 'search',
    params: { page: 1, pageSize: 5 }, idField: 'id', titleFields: ['contractNumber', 'contractTitle'],
    subtitleFields: ['businessPartnerName'], statusField: 'status', detailPath: '/procurement/contracts/:id' },
  { id: 'procurement-supplier-invoices', module: 'Procurement', label: 'Supplier invoice',
    route: '/procurement/supplier-invoices', endpoint: '/ap/invoices', searchParam: 'searchTerm',
    params: { page: 1, pageSize: 5, procurementOnly: true }, idField: 'id', titleFields: ['invoiceNumber'],
    subtitleFields: ['supplierInvoiceNumber'], statusField: 'status', detailPath: '/procurement/supplier-invoices/:id' },
  { id: 'business-partners', module: 'Procurement', label: 'Business partner',
    route: '/procurement/business-partners', endpoint: '/procurement/business-partners', searchParam: 'search',
    params: { page: 1, pageSize: 5 }, idField: 'id', titleFields: ['partnerCode', 'partnerName'],
    subtitleFields: ['partnerType'], statusField: 'status', detailPath: '/procurement/business-partners/:id' },
  { id: 'purchase-requisitions', module: 'Procurement', label: 'Purchase requisition',
    route: '/procurement/purchase-requisitions', endpoint: '/PurchaseRequisitions', searchParam: 'search',
    params: { page: 1, pageSize: 5 }, idField: 'id', titleFields: ['requisitionNumber'],
    subtitleFields: ['organizationUnitName', 'sourcePlanNumber'], statusField: 'status', detailPath: '/procurement/purchase-requisitions/:id' },
  { id: 'purchase-orders', module: 'Procurement', label: 'Purchase order',
    route: '/procurement/purchase-orders', endpoint: '/PurchaseOrders', searchParam: 'search',
    params: { page: 1, pageSize: 5 }, idField: 'id', titleFields: ['orderNumber'],
    subtitleFields: ['supplierName', 'procurementSourceReference'], statusField: 'status', detailPath: '/procurement/purchase-orders/:id' },
  { id: 'purchase-receipts', module: 'Procurement', label: 'Goods receipt',
    route: '/procurement/purchase-receipts', endpoint: '/PurchaseOrderReceipts', searchParam: 'search',
    params: { page: 1, pageSize: 5 }, idField: 'id', titleFields: ['receiptNumber'],
    subtitleFields: ['purchaseOrderNumber', 'supplierName'], statusField: 'status', detailPath: '/procurement/purchase-receipts/:id' },
  { id: 'tenders', module: 'Procurement', label: 'Tender',
    route: '/procurement/tenders', endpoint: '/procurement/Tenders', searchParam: 'search',
    params: { page: 1, pageSize: 5 }, idField: 'id', titleFields: ['tenderNumber', 'title'],
    statusField: 'status', detailPath: '/procurement/tenders/:id' },
  { id: 'rfqs', module: 'Procurement', label: 'Request for quotation',
    route: '/procurement/rfqs', endpoint: '/procurement/rfqs', searchParam: 'search',
    params: { page: 1, pageSize: 5 }, idField: 'id', titleFields: ['rfqNumber', 'title'],
    statusField: 'status', detailPath: '/procurement/rfqs/:id/controls' },
];
