import type { GlobalSearchRecordSource } from './global-search';

export const GLOBAL_SEARCH_CIVIL_QS_SOURCES: GlobalSearchRecordSource[] = [
  ...[
    { id: 'qs-rate-library', label: 'Rate library items', module: 'Quantity Survey',
      route: '/administration/project-management/quantity-survey-rate-library', endpoint: '/quantity-survey/rate-library',
      titleFields: ['code', 'name'], subtitleFields: ['description', 'unitOfMeasureCode'],
      detailPath: '/development/quantity-survey/search-result?kind=rate-library&recordId=:id',
      permissions: ['quantity-survey.workspace.read'] },
    { id: 'qs-price-index-imports', label: 'Price-index imports', module: 'Quantity Survey',
      route: '/administration/project-management/quantity-survey-escalation', endpoint: '/quantity-survey/price-index-imports',
      titleFields: ['indexFamilyCode', 'originalFileName'], subtitleFields: ['indexFamilyName'], statusField: 'status',
      detailPath: '/development/quantity-survey/search-result?kind=price-index-imports&recordId=:id',
      permissions: ['quantity-survey.workspace.read'] },
    { id: 'qs-escalation-formulas', label: 'Escalation formulas', module: 'Quantity Survey',
      route: '/administration/project-management/quantity-survey-escalation', endpoint: '/quantity-survey/escalation-formulas',
      titleFields: ['code', 'name'], subtitleFields: ['contractNumber', 'projectName'], statusField: 'status',
      detailPath: '/development/quantity-survey/search-result?kind=escalation-formulas&recordId=:id',
      permissions: ['quantity-survey.workspace.read'] },
    { id: 'qs-configuration-profiles', label: 'QS configuration profiles', module: 'Quantity Survey',
      route: '/administration/project-management/quantity-survey-config', endpoint: '/quantity-survey/configuration-profiles',
      titleFields: ['profileCode', 'name'], subtitleFields: ['version'], statusField: 'lifecycleStatus',
      detailPath: '/administration/project-management/quantity-survey-config/:id',
      permissions: ['quantity-survey.configuration.read'] },
    { id: 'civil-configuration-profiles', label: 'Civil configuration profiles', module: 'Civil Engineering',
      route: '/administration/project-management/civil-engineering-config', endpoint: '/civil-engineering/configuration-profiles',
      titleFields: ['profileCode', 'name'], subtitleFields: ['version'], statusField: 'lifecycleStatus',
      detailPath: '/administration/project-management/civil-engineering-config/:id',
      permissions: ['civil-engineering.configuration.read'] },
  ].map(source => ({ ...source, searchParam: 'search', params: { page: 1, pageSize: 5 }, itemsPath: 'items', idField: 'id' })),
  {
    id: 'civil-direct-tasks', module: 'Civil Engineering', label: 'Direct tasks',
    route: '/development/civil-engineering/direct-tasks', endpoint: '/civil-engineering/direct-tasks/search',
    searchParam: 'search', params: { take: 5 }, itemsPath: '', idField: 'id',
    titleFields: ['title'], subtitleFields: ['assignedToName', 'instructions'], statusField: 'status',
    detailPath: '/development/quantity-survey/search-result?kind=civil-task&recordId=:id',
    permissions: ['civil-engineering.workspace.read'],
  },
  ...[
    { id: 'measurements', label: 'Measurement sheets', titleFields: ['sheetReference', 'title'], idField: 'id' },
    { id: 'valuation-worksheets', label: 'Valuation worksheets', titleFields: ['interimValuationLabel'], idField: 'projectInterimValuationId' },
    { id: 'variations', label: 'Variations', titleFields: ['referenceNumber', 'title'], idField: 'id' },
    { id: 'payment-certificates', label: 'Payment certificates', titleFields: ['certificateNumber', 'title'], idField: 'id' },
  ].map((source) => ({
    ...source, id: `qs-${source.id}`, module: 'Quantity Survey', route: '/development/projects',
    endpoint: `/quantity-survey/${source.id}/search`, searchParam: 'search', params: { take: 5 },
    itemsPath: '', statusField: 'status', permissions: ['quantity-survey.workspace.read'],
    detailPath: `/development/quantity-survey/search-result?kind=${source.id}&recordId=:id`,
  })),
  {
    id: 'qs-catalogues', module: 'Quantity Survey', label: 'Catalogue entries',
    route: '/administration/project-management/quantity-survey-catalogues',
    endpoint: '/quantity-survey/catalogues/search', searchParam: 'search', params: { take: 5 },
    itemsPath: '', idField: 'id', titleFields: ['code', 'name'], subtitleFields: ['catalogType', 'description'],
    permissions: ['quantity-survey.configuration.read'],
    detailPath: '/development/quantity-survey/search-result?kind=catalogues&recordId=:id',
  },
];
